<script setup lang="ts">
import {computed,ref,shallowRef,watch} from 'vue'
import {useRoutingPack} from '../../papers/useRoutingPack'
import type {RouteLayer} from '../../papers/sparseTraces'
import Legacy from './ExpertRoutingLegacy.vue'
const {pack,provenance,error,busy,load,layer}=useRoutingPack()
const level=ref(0),cases=ref([0,1]),tokens=ref([0,0]),rows=shallowRef<RouteLayer[]>([]),failure=ref(''),loading=ref(false)
let request=0
watch([pack,level,()=>cases.value.join(',')],async()=>{const ticket=++request;rows.value=[];failure.value='';if(!pack.value)return;loading.value=true
 try{const result=await Promise.all(cases.value.map(c=>layer(c,level.value)));if(ticket===request)rows.value=result}catch(e){if(ticket===request)failure.value=String(e)}finally{if(ticket===request)loading.value=false}}, {flush:'sync'})
function changeCase(side:number){tokens.value[side]=0}
function reset(){level.value=0;cases.value=[0,1];tokens.value=[0,0]}
const loads=computed(()=>rows.value.map((r,side)=>{const n=Array.from({length:pack.value!.experts},()=>({calls:0,mass:0}));r.selected.forEach((ids,i)=>{if(!pack.value!.cases[cases.value[side]].tokens[i].padding)ids.forEach((e,j)=>{n[e].calls++;n[e].mass+=r.weights[i][j]})});return n}))
const scores=ref([2,1,0,-1,0,0,-2,1])
const gate=computed(()=>{const m=Math.max(...scores.value),ex=scores.value.map(x=>Math.exp(x-m)),sum=ex.reduce((a,b)=>a+b,0);const p=ex.map(x=>x/sum),top=p.map((v,i)=>({v,i})).sort((a,b)=>b.v-a.v).slice(0,2);return p.map((v,i)=>({p:v,w:top.some(x=>x.i===i)?v/top.reduce((a,b)=>a+b.v,0):0}))})
</script>
<template><section class="paper-lab"><h3>同一个词，换个语境会选谁？</h3><p>选择完整路由包中的 manifest.json 和所有层文件。先定位两个语境中的目标 token，再切换层观察路由；显示文字相同不代表 token ID 相同。</p><input type="file" multiple accept=".json" aria-label="导入路由包" @change="reset();load($event)"><p v-if="error||failure" role="alert">{{error||failure}}</p><p v-if="busy||loading">读取并校验层记录…</p><details v-if="provenance"><summary>记录来源（由提供者声明）</summary><pre>{{provenance}}</pre></details>
<template v-if="pack"><label>共同观察层 <select v-model.number="level"><option v-for="(l,i) in pack.cases[0].layers" :value="i" :key="i">{{l.name}}</option></select></label><p>总参数 {{pack.parameter_counts.total.toLocaleString()}}；专家参数 {{pack.parameter_counts.expert_total.toLocaleString()}}。每 token 调用 {{pack.top_k}} / {{pack.experts}} 个专家，不等于只存储这些专家。</p><div class="compare"><article v-for="side in [0,1]" :key="side"><select v-model.number="cases[side]" :aria-label="`语境${side+1}`" @change="changeCase(side)"><option v-for="(c,i) in pack.cases" :value="i" :key="c.id">{{c.id}}</option></select><p>{{pack.cases[cases[side]].text}}</p><div class="tokens"><button v-for="(t,i) in pack.cases[cases[side]].tokens" :key="i" :aria-pressed="tokens[side]===i" @click="tokens[side]=i">{{t.text}} · {{t.id}}{{t.padding?' PAD':''}}</button></div><template v-if="rows[side]"><svg viewBox="0 0 440 300" role="img" aria-label="当前token的专家分流与加权合并"><text x="4" y="22">输入 [1, {{pack.hidden_size}}]</text><g v-for="(e,j) in rows[side].selected[tokens[side]]" :key="e"><path :d="`M 60 40 L 210 ${65+j*28} L 360 275`" fill="none" stroke="#2563eb" :stroke-width="2+rows[side].weights[tokens[side]][j]*5"/><rect x="140" :y="50+j*28" width="160" height="24" fill="#dbeafe"/><text x="146" :y="67+j*28">E{{e}} × {{rows[side].weights[tokens[side]][j].toFixed(4)}}</text></g><text x="190" y="295">Σ → [1, {{pack.hidden_size}}]</text></svg><table><thead><tr><th>专家</th><th>当前路由概率</th><th>非PAD调用次数</th><th>加权质量</th></tr></thead><tbody><tr v-for="(item,e) in loads[side]" :key="e"><td>E{{e}}</td><td>{{rows[side].probabilities[tokens[side]][e].toFixed(4)}}</td><td>{{item.calls}}</td><td>{{item.mass.toFixed(3)}}</td></tr></tbody></table><p>调用次数合计 = 非 PAD token 数 × K；加权质量合计约等于非 PAD token 数。两者都不是耗时。</p></template></article></div></template>
<details :open="!pack"><summary>无权重练习：亲手改变 gate 分数</summary><p>这是手动数学算例，不是模型输出。softmax(z) → Top-2 → 选中概率重新归一化；相同分数按编号打破平局。</p><div v-for="(g,i) in gate" :key="i"><label>E{{i}} <input v-model.number="scores[i]" type="range" min="-5" max="5" step=".1"> {{scores[i]}}</label> p={{g.p.toFixed(4)}} → 合并权重 {{g.w.toFixed(4)}}</div></details><p>没有专家输出向量时只展示路由和维度；不能从一次选择给专家命名为“数学专家”。</p><details><summary>兼容旧版单文件记录</summary><Legacy/></details></section></template>
<style scoped>.compare{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.compare article{min-width:0;overflow:auto}svg{width:100%}text{font-size:13px}pre{white-space:pre-wrap;overflow-wrap:anywhere}@media(max-width:800px){.compare{grid-template-columns:1fr}}</style>
