<script setup lang="ts">
import {computed,ref,shallowRef} from 'vue'
import TraceLoader from './TraceLoader.vue'
import GoBoard from './GoBoard.vue'
import GoRulesLab from './GoRulesLab.vue'
import {goMove} from '../../papers/boardRules'
import {parseGo,goCoordinate,parentValue,type GoNode} from '../../papers/searchTraces'
import {research} from '../../papers/research'
const data=shallowRef<ReturnType<typeof parseGo>|null>(null),snapshot=ref(0),selected=ref(''),guess=ref<number|null|undefined>(),error=ref(''),revealed=ref(false),c=ref(1.4)
const current=computed(()=>data.value?.snapshots[snapshot.value]),position=computed(()=>current.value?.nodes.find(n=>n.id===selected.value)??current.value?.nodes[0])
const children=computed(()=>current.value?.nodes.filter(n=>n.parent===position.value?.id)??[])
const roots=computed(()=>current.value?.nodes.filter(n=>n.parent===current.value?.nodes[0].id)??[])
const path=computed(()=>{const nodes=current.value?.nodes??[],out:GoNode[]=[];let n=position.value;while(n){out.unshift(n);n=nodes.find(p=>p.id===n!.parent)}return out})
const layout=computed(()=>{const nodes=current.value?.nodes??[],depth=new Map<string,number>(),levels:number[]=[];return nodes.map(n=>{const d=n.parent?(depth.get(n.parent)??0)+1:0;depth.set(n.id,d);const order=levels[d]??0;levels[d]=order+1;return {...n,x:65+order*125,y:40+d*100}})})
const width=computed(()=>Math.max(500,...layout.value.map(n=>n.x+75))),height=computed(()=>Math.max(180,...layout.value.map(n=>n.y+65)))
const labels=computed(()=>Object.fromEntries(children.value.filter(n=>n.move!==null).map((n,i)=>[n.move!,String(i+1)])))
const evidence=research['02'].experiments[0],metric=ref(0)
function accept(v:unknown){data.value=parseGo(v);snapshot.value=0;selected.value=data.value.snapshots[0].nodes[0].id;guess.value=undefined;revealed.value=false;error.value=''}
function changeBudget(){selected.value=current.value?.nodes[0].id??''}
function choose(m:number|null){if(!data.value||!current.value)return;const root=current.value.nodes[0];try{goMove(root.board,data.value.size,m,root.to_play,[...data.value.root_history,root.board]);guess.value=m;error.value=''}catch(e){error.value=String(e)}}
function boardClick(m:number){if(position.value?.parent===null&&!revealed.value)choose(m);else {const child=children.value.find(n=>n.move===m);if(child)selected.value=child.id}}
function best(field:'prior'|'visits'){const max=Math.max(...roots.value.map(n=>n[field]));return roots.value.filter(n=>n[field]===max).map(n=>goCoordinate(n.move,data.value!.size)).join(' / ')}
function u(n:GoNode){return c.value*n.prior*Math.sqrt(position.value?.visits??0)/(1+n.visits)}
</script>
<template><section class="paper-lab"><h3>AlphaGo：先看合法分支，再看搜索为什么改选</h3><GoRulesLab/><h4>接入真实搜索记录</h4><p>下面的先验、价值、访问次数全部来自导入记录。尚无记录时保持空白；上方提子题不会生成模型概率。</p><TraceLoader paper-id="02" :validate="parseGo" @loaded="accept" @clear="data=null;error=''"/>
<template v-if="data&&current&&position"><div class="controls"><label>实际预算 {{current.budget}}<input v-model.number="snapshot" type="range" min="0" :max="data.snapshots.length-1" @input="changeBudget"></label><button @click="selected=current.nodes[0].id">回到根局面</button><button :disabled="!position.parent" @click="selected=position.parent??selected">回父节点</button></div><p>先在根棋盘预测一手，再揭开记录；预算滑块只选择已记录快照。</p><button v-if="!revealed" @click="choose(null)">预测 PASS</button> <button v-if="!revealed" @click="revealed=true">揭示搜索统计</button><p>你的根落子预测：{{guess===undefined?'未选':goCoordinate(guess,data.size)}}</p><p v-if="error" role="alert">{{error}}</p><div class="controls"><GoBoard :board="position.board" :size="data.size" :mark="position.parent===null?guess:position.move" :labels="revealed?labels:{}" @choose="boardClick"/><div><p>当前 {{position.id}}，轮到{{position.to_play===1?'黑':'白'}}。</p><div class="controls"><button v-for="n in path" :key="n.id" @click="selected=n.id">{{n.parent===null?'ROOT':goCoordinate(n.move,data.size)}}</button></div><p v-if="revealed">棋盘编号对应当前节点的子分支，点击编号进入；PASS 分支从下方表格进入。棋盘与整棵树同步。</p></div></div>
<template v-if="revealed"><p v-if="roots.length">已记录根分支中：先验最大 {{best('prior')}}；访问最大 {{best('visits')}}。并列全部列出，不擅自选择赢家。</p><p>已记录根先验总和 {{roots.reduce((s,n)=>s+n.prior,0).toFixed(4)}}。导出的树可能被裁剪，未记录分支不等于概率0；最大候选不必是引擎最终实际落子。</p><div class="tree"><svg :width="width" :height="height" :viewBox="`0 0 ${width} ${height}`" aria-label="搜索树，可点击节点"><template v-for="n in layout" :key="n.id"><line v-if="n.parent" :x1="layout.find(p=>p.id===n.parent)?.x" :y1="layout.find(p=>p.id===n.parent)?.y" :x2="n.x" :y2="n.y" stroke="#94a3b8"/><g role="button" tabindex="0" :aria-label="`${n.id}，访问 ${n.visits}`" @click="selected=n.id" @keydown.enter="selected=n.id"><circle :cx="n.x" :cy="n.y" r="23" :fill="n.id===position.id?'#2563eb':'#e2e8f0'"/><text :x="n.x" :y="n.y+4" text-anchor="middle" :fill="n.id===position.id?'white':'#0f172a'">{{n.parent?goCoordinate(n.move,data.size):'根'}}</text><text :x="n.x" :y="n.y+39" text-anchor="middle">N={{n.visits}}</text></g></template></svg></div>
<p>价值原始视角：{{data.value_perspective}}。下表换算到当前父节点行动方；不能直接把对手视角高值当作我方好结果。</p><label v-if="data.statistics">教学探索系数 c={{c}}<input v-model.number="c" type="range" min="0" max="4" step="0.1"></label><table><thead><tr><th>落点 / 节点</th><th>P</th><th>N</th><th>父方价值</th><th v-if="data.statistics">教学 Q+U</th></tr></thead><tbody><tr v-for="(n,i) in children" :key="n.id"><td><button @click="selected=n.id">{{i+1}} · {{goCoordinate(n.move,data.size)}} / {{n.id}}</button></td><td>{{n.prior.toFixed(4)}}</td><td>{{n.visits}}</td><td>{{parentValue(n,position,data.value_perspective).toFixed(4)}}</td><td v-if="data.statistics">{{(parentValue(n,position,data.value_perspective)+u(n)).toFixed(4)}}</td></tr></tbody></table><p v-if="!children.length">没有导出这个节点的子分支，不能推断它是终局。</p><p v-if="data.statistics" class="note">仅用记录统计试算 U=c·P·√N父/(1+N子)，修改 c 不重跑搜索、不改变记录。不是原版 AlphaGo 的完整选择公式；不包含虚拟损失、混合 rollout 估值和并行调度。</p><p v-else class="note">旧记录没有明确完成模拟计数约定，仅显示来源值，不据此计算探索项。</p></template><p class="note">根前历史{{data.root_history.length?'由记录声明，纳入超级劫检查':'缺失，超级劫只在本树路径检查'}}；不重建终局计分、不执行围棋引擎。stats v2 检查访问数与先验约束不能证明记录真实。</p></template>
<h4>回到原文：快的和准的为什么都需要？</h4><select v-model.number="metric"><option :value="0">专家落子预测准确率</option><option :value="1">一次动作选择耗时</option></select><div class="cards"><article v-for="r in evidence.rows" :key="r.name"><b>{{r.name}}</b><p>{{r.values[metric]}} {{evidence.metrics[metric].unit}}</p></article></div><p>这些是原文策略模块的指标，不是网页测速，也不是整局胜率。来源：{{evidence.source.label}}，页 {{evidence.source.pages.join('、')}}。</p></section></template>
<style scoped>.tree{overflow:auto;max-height:520px;border:1px solid #cbd5e1}.tree svg{max-width:none;width:auto;display:block}.tree text{font-size:11px}.tree g{cursor:pointer}</style>
