<script setup lang="ts">
import { ref,shallowRef,computed,watch } from 'vue'
import TraceLoader from './TraceLoader.vue'
import LanguageModelStatus from './LanguageModelStatus.vue'
import { envelope } from '../../papers/traceValidation'
import { parseGpt } from '../../papers/languageTraces'
import { useLocalLanguage,downloadLanguageRecord } from '../../papers/useLocalLanguage'
const examples=['A small town opened a new public library on Monday. The library offers free books and evening classes.','On Monday, the museum announced a new exhibition about ocean life. Tickets are free for children.']
const article=ref(examples[0]),kind=ref(0),step=ref(0),maxTokens=ref(48),meta=ref(''),selection=ref(''),verdict=ref('')
const suffixes=['\n','\nTL;DR:','\nQuestion: What was announced or opened on Monday?\nAnswer:'],names=['继续写','压缩为摘要','回答一个问题']
const data=shallowRef<ReturnType<typeof parseGpt>|null>(null),sourceArticle=ref('')
const current=computed(()=>data.value?.conditions[kind.value])
const prefixParts=computed(()=>{const t=current.value?.text??'';return sourceArticle.value&&t.startsWith(sourceArticle.value)?{article:sourceArticle.value,suffix:t.slice(sourceArticle.value.length)}:{article:t,suffix:''}})
const local=useLocalLanguage('07'),{config,busy,error}=local
function clear(){local.invalidate();data.value=null;meta.value='';step.value=0;selection.value='';verdict.value='';sourceArticle.value=''}
watch([article,maxTokens],clear,{flush:'sync'});watch(kind,()=>{step.value=0;selection.value='';verdict.value=''})
function accept(v:unknown){data.value=parseGpt(v);kind.value=0;step.value=0;meta.value='导入记录：完整输入以记录为准，不把编辑框内容当作记录原文。'}
function receive(v:unknown){const e=envelope(v,'07');accept(e.data);sourceArticle.value=article.value;meta.value=JSON.stringify(e.provenance,null,2)}
function start(){clear();local.run(suffixes.map(s=>article.value+s),receive,maxTokens.value)}
</script>
<template><section class="paper-lab"><h3>模型只会续写，任务从哪里来？</h3><div class="controls"><button v-for="(_,i) in examples" :key="i" @click="article=examples[i]">固定文章 {{i+1}}</button></div><textarea v-model="article" maxlength="1500" aria-label="文章原文"/><label>每条件最多 {{maxTokens}} 个新 token<input v-model.number="maxTokens" type="range" min="8" max="128" step="8"></label><div class="cards"><article v-for="(s,i) in suffixes" :key="i"><b>{{names[i]}}</b><pre>{{s||'换行'}}</pre></article></div><button :disabled="busy||!config?.configured||!article.trim()" @click="start">同一文章，运行三个后缀</button><LanguageModelStatus :config="config" :busy="busy" :error="error" @refresh="local.refresh" @cancel="local.cancel"/><TraceLoader paper-id="07" :validate="parseGpt" @loaded="accept" @clear="clear"/>
<template v-if="data&&current"><div class="controls"><button v-for="(c,i) in data.conditions" :key="i" :aria-pressed="kind===i" @click="kind=i">{{sourceArticle?names[i]:`条件 ${i+1}`}}</button></div><p>蓝：原文或导入完整前缀；橙：任务后缀；绿：模型追加。条件切换会从零回放。</p><div class="editor"><span class="article">{{prefixParts.article}}</span><span class="suffix">{{prefixParts.suffix}}</span><span class="output">{{current.generated.slice(0,step).map(t=>t.piece).join('')}}</span><b class="cursor">│</b></div><div class="controls"><button :disabled="step===0" @click="step--">退一个 token</button><button :disabled="step===current.generated.length" @click="step++">追加一个 token</button><button @click="step=current.generated.length">全部展开</button></div><label>{{step}} / {{current.generated.length}}<input v-model.number="step" type="range" min="0" :max="current.generated.length"></label><p v-if="step>0">第 {{step}} 步：取 logits [1, V] → softmax → argmax；token ID {{current.generated[step-1].id}}，p={{current.generated[step-1].p.toFixed(5)}}。输入长度 {{current.input_ids.length}} → 已追加后长度 {{current.input_ids.length+step}}。</p><details><summary>完整解码结果、输入 ID 与停止原因</summary><p>{{current.output||'模型只生成了结束符，没有可见回答'}}</p><p>{{current.stop_reason==='eos'?'遇到 EOS':'达到长度上限，回答可能未完成'}}</p><pre>{{current.input_ids}}</pre></details><fieldset><legend>回到原文核查一句输出</legend><label>复制待核查内容<input v-model="selection" maxlength="200"></label><div class="controls"><button v-for="v in ['原文支持','原文未说明','与原文冲突']" :key="v" :aria-pressed="verdict===v" @click="verdict=v">{{v}}</button></div><p v-if="selection&&verdict">你的暂存标注：{{selection}} → {{verdict}}。这是读者判断，不参与模型概率或自动评分；重要结论可记到课末笔记。</p></fieldset><button v-if="local.trace.value" @click="downloadLanguageRecord(local.trace.value,'07')">导出实际模型记录</button><details><summary>来源</summary><pre>{{meta}}</pre></details></template><p class="note">这是完成推理后的回放，不是实时流式生成。单 token 解码可能出现不完整字符，完整 output 才是最终文本。这里没有微调或新的任务头；生成概率不能证明事实正确。</p></section></template>
<style scoped>.editor{padding:20px;white-space:pre-wrap;line-height:2.3;border:1px solid #cbd5e1;border-radius:8px}.article{background:#dbeafe}.suffix{background:#ffedd5}.output{background:#dcfce7}.cursor{color:#16a34a}</style>
