<script setup lang="ts">
import {computed,ref,shallowRef,watch,onUnmounted} from 'vue'
import TraceLoader from './TraceLoader.vue'
import Legacy from './MultimodalDenoiseLegacy.vue'
import {parseDenoise,transition,type DenoiseTrace} from '../../papers/sparseTraces'
const data=shallowRef<DenoiseTrace|null>(null),index=ref(0),pin=ref(0),position=ref(0),playing=ref(false),pictures=ref<(string|null)[]>([null,null]),error=ref('')
let timer:ReturnType<typeof setInterval>|undefined,sequence=0
function stop(){if(timer)clearInterval(timer);timer=undefined;playing.value=false}
function clear(){stop();data.value=null;index.value=pin.value=position.value=0;pictures.value=[null,null];++sequence}
function accept(v:unknown){clear();data.value=parseDenoise(v)}
function play(){if(playing.value){stop();return}if(!data.value)return;if(index.value===data.value.frames.length-1)index.value=0;playing.value=true;timer=setInterval(()=>{if(!data.value||index.value>=data.value.frames.length-1){stop();return}index.value++},900)}
const current=computed(()=>data.value?.frames[index.value]),reference=computed(()=>data.value?.frames[pin.value])
const changes=computed(()=>{const counts:Record<string,number>={'恢复':0,'再遮蔽':0,'改写':0,'不变':0};if(current.value&&reference.value)data.value!.positions.forEach((_,i)=>counts[transition(reference.value!,current.value!,i)]++);return counts})
watch([current,reference],async()=>{const ticket=++sequence;pictures.value=[null,null];error.value='';const d=data.value;if(!d)return
 try{const result=await Promise.all([reference.value,current.value].map(f=>new Promise<string|null>((resolve,reject)=>{if(!f?.decoded_image){resolve(null);return}const src=f.decoded_image,img=new Image();img.onload=()=>{if(img.naturalWidth!==d.image_shape?.width||img.naturalHeight!==d.image_shape?.height){reject(Error('解码图片实际尺寸与声明不一致'));return}resolve(src)};img.onerror=()=>reject(Error('图片无法解码'));img.src=src})));if(ticket===sequence)pictures.value=result}catch(e){if(ticket===sequence)error.value=String(e)}})
onUnmounted(()=>{stop();++sequence})
const exercise=ref<boolean[]>(Array(12).fill(false)),mode=ref('parallel')
function reveal(i:number){if(mode.value==='ar'&&i!==exercise.value.indexOf(false))return;exercise.value[i]=!exercise.value[i]}
</script>
<template><section class="paper-lab"><h3>同一段生成过程，哪些位置先确定，哪些又被改写？</h3><TraceLoader paper-id="25" :validate="parseDenoise" @loaded="accept" @clear="clear"/><template v-if="data&&current&&reference"><div class="controls"><button @click="play">{{playing?'暂停':'播放'}}</button><button :disabled="index===0" @click="stop();index--">上一帧</button><input v-model.number="index" type="range" min="0" :max="data.frames.length-1" aria-label="生成帧" @input="stop"><button :disabled="index===data.frames.length-1" @click="stop();index++">下一帧</button><button @click="pin=index">固定当前帧作参照</button></div><p>参照 step {{reference.step}} → 当前 step {{current.step}}。<span v-for="(n,label) in changes" :key="label">{{label}} {{n}}；</span></p><p v-if="pin>index">当前帧早于参照帧；变化统计方向是参照 → 当前，不是时间向前。</p><p v-if="error" role="alert">{{error}}</p><div class="frames"><article v-for="(f,j) in [reference,current]" :key="j"><h4>{{j?'当前':'参照'}} · step {{f.step}}</h4><p>{{f.decoded_text||'此帧没有解码文本'}}</p><img v-if="pictures[j]" :src="pictures[j]!" alt="记录中的实际解码图像"><p v-else>此帧没有通过校验的解码图像。</p></article></div><h4>位置带：点击追踪一个位置</h4><div class="tokens"><button v-for="(p,i) in data.positions" :key="i" :aria-pressed="position===i" :class="{mask:current.masked[i],fixed:p.condition}" @click="position=i">{{i}} {{p.kind==='image'?'图像码':'文本'}} {{current.masked[i]?'MASK':current.tokens[i]}} · {{transition(reference,current,i)}}{{p.condition?' 固定条件':''}}</button></div><template v-if="data.image_grid"><h4>图像离散码网格（数字不是像素颜色）</h4><div class="code-grid" :style="{gridTemplateColumns:`repeat(${data.image_grid.cols},minmax(48px,1fr))`}"><template v-for="(p,i) in data.positions" :key="i"><button v-if="p.kind==='image'" @click="position=i">{{current.masked[i]?'MASK':current.token_ids[i]}}</button></template></div></template><h4>位置 {{position}} 的时间线</h4><table><thead><tr><th>step</th><th>token ID</th><th>状态</th><th>记录置信度</th></tr></thead><tbody><tr v-for="(f,i) in data.frames" :key="f.step" :class="{active:i===index}"><td><button @click="stop();index=i">{{f.step}}</button></td><td>{{f.token_ids[position]}}</td><td>{{f.masked[position]?'MASK':f.tokens[position]}}</td><td>{{f.confidence[position]?.toFixed(4)??'未提供'}}</td></tr></tbody></table><p>tokenizer：{{data.tokenizer_revision}}；decoder：{{data.decoder_revision}}。不同轮次的置信度定义由记录 settings 说明，不能当作答案正确率。</p></template><details :open="!data"><summary>无模型练习：位置顺序为何不同？</summary><p>这里只操作位置，不生成文字或图片。左到右练习只能揭开下一个位置；并行位置练习允许选择任意位置。真实扩散采样还需要模型预测与重遮蔽策略。</p><select v-model="mode" @change="exercise=Array(12).fill(false)"><option value="parallel">任意位置练习</option><option value="ar">左到右练习</option></select><button @click="exercise=Array(12).fill(false)">重置</button><div class="tokens"><button v-for="(open,i) in exercise" :key="i" :disabled="mode==='ar'&&i!==exercise.indexOf(false)" @click="reveal(i)">{{i}} · {{open?'可见':'MASK'}}</button></div></details><p>采样步骤不是训练阶段：Mixed Long CoT、UniGRPO 的消融证据见下方原文实验。</p><details><summary>兼容旧版单文件记录</summary><Legacy/></details></section></template>
<style scoped>.frames{display:grid;grid-template-columns:1fr 1fr;gap:16px}.frames img{max-width:100%}.frames p{white-space:pre-wrap}.mask{background:#e2e8f0}.fixed{border:2px solid #059669}.active{background:#dbeafe}.code-grid{display:grid;gap:3px;overflow:auto}.code-grid button{font-size:11px}@media(max-width:700px){.frames{grid-template-columns:1fr}}</style>
