<script setup lang="ts">
import {ref,shallowRef,computed} from 'vue'
import TraceLoader from './TraceLoader.vue'
import {parsePreferences} from '../../papers/trainingTraces'
import {downloadSearch} from '../../papers/ticSearch'
const fixture={items:[{prompt:'请用一句话概括：社区图书馆周一开放，每周三有免费阅读活动。',responses:[{stage:'本站手写练习（无训练阶段）',text:'社区图书馆周一开放，周三提供免费阅读活动。',reward:null},{stage:'本站手写练习（无训练阶段）',text:'这家大型图书馆每天免费提供阅读活动，还配有游泳池。',reward:null},{stage:'本站手写练习（无训练阶段）',text:'图书馆开放了。\n每周有活动。\n大家可以参加。',reward:null}]}]}
const data=shallowRef(parsePreferences(fixture)),source=ref('本站手写评价练习，不是模型输出'),meta=shallowRef<unknown>(null),item=ref(0),order=ref<number[]>([]),labels=ref<Record<number,string>>({}),revealed=ref(false),confirmed=ref(false),criterion=ref('遵循指令'),flow=ref(0)
const rounds=ref<{item:number;order:number[];criterion:string;blind:boolean}[]>([]),everSeen=ref<Record<number,boolean>>({})
const current=computed(()=>data.value.items[item.value])
function shuffle(){const indices=current.value.responses.map((_,i)=>i);for(let i=indices.length-1;i>0;i--){const v=new Uint32Array(1);crypto.getRandomValues(v);const j=v[0]%(i+1);[indices[i],indices[j]]=[indices[j],indices[i]]}order.value=indices;labels.value=Object.fromEntries(indices.map((id,i)=>[id,String.fromCharCode(65+i)]));revealed.value=false;confirmed.value=false}
shuffle()
function clear(){data.value=parsePreferences(fixture);source.value='本站手写评价练习，不是模型输出';meta.value=null;item.value=0;rounds.value=[];everSeen.value={};shuffle()}
function accept(v:unknown){data.value=parsePreferences(v);source.value='导入的实际输出，来源由提供者声明';item.value=0;rounds.value=[];everSeen.value={};shuffle()}
function move(i:number,d:number){const j=i+d;if(j<0||j>=order.value.length||confirmed.value)return;const next=[...order.value];[next[i],next[j]]=[next[j],next[i]];order.value=next}
function reveal(){rounds.value.push({item:item.value,order:[...order.value],criterion:criterion.value,blind:!everSeen.value[item.value]});confirmed.value=true;revealed.value=true;everSeen.value[item.value]=true}
const disagreement=computed(()=>{const rows=rounds.value.filter(r=>r.item===item.value&&r.criterion===criterion.value);if(rows.length<2)return null;const a=rows[rows.length-2].order,b=rows[rows.length-1].order;let changed=0,total=0;for(let i=0;i<a.length;i++)for(let j=i+1;j<a.length;j++){total++;if(b.indexOf(a[i])>b.indexOf(a[j]))changed++}return {changed,total}})
const rewardPairs=computed(()=>{if(!revealed.value)return null;let agree=0,total=0;for(let i=0;i<order.value.length;i++)for(let j=i+1;j<order.value.length;j++){const a=current.value.responses[order.value[i]].reward,b=current.value.responses[order.value[j]].reward;if(a!==null&&b!==null&&a!==b){total++;if(a>b)agree++}}return {agree,total}})
const stages=[{name:'SFT',detail:'人工示范用于监督学习完整回答；当前拖动卡片没有创建或执行SFT训练。'},{name:'奖励模型',detail:'回答之间的偏好可构成chosen/rejected对；必须另行训练奖励模型，排序本身不是奖励函数。'},{name:'策略优化',detail:'原文用奖励信号与约束优化策略，再做人类评价；网页没有PPO或参数更新。'}]
</script>
<template><section class="paper-lab"><h3>先评回答，再看它的名字</h3><p>{{source}}。默认例子用来练习评价准则，不标成base/SFT/RLHF的输出。</p><button @click="clear">回到固定手写练习</button><TraceLoader paper-id="13" :validate="parsePreferences" :hide-metadata="!revealed" @loaded="accept" @provenance="meta=$event" @clear="clear"/><label>题目<select v-model.number="item" @change="shuffle"><option v-for="(_,i) in data.items" :key="i" :value="i">{{i+1}}</option></select></label><label>本轮准则<select v-model="criterion" :disabled="confirmed"><option>遵循指令</option><option>事实依据</option><option>简洁有用</option></select></label><h4>{{current.prompt}}</h4><article v-for="(index,rank) in order" :key="index" class="response"><b>偏好 {{rank+1}} · 匿名回答 {{labels[index]}}</b><p>{{current.responses[index].text}}</p><button :disabled="rank===0||confirmed" @click="move(rank,-1)">上移</button> <button :disabled="rank===order.length-1||confirmed" @click="move(rank,1)">下移</button><p v-if="revealed">阶段 {{current.responses[index].stage}}；记录奖励 {{current.responses[index].reward??'未提供'}}</p></article><button :disabled="confirmed" @click="reveal">确认本轮排序并揭示</button> <button @click="shuffle">重新洗牌评价</button><p v-if="everSeen[item]" class="note">你已看过此题来源；再评标为“已知来源复评”，不能算独立盲评。</p><p v-if="rewardPairs">读者排序与记录奖励一致：{{rewardPairs.agree}} / {{rewardPairs.total}} 个可比较对（无奖励、奖励相等的对排除）。奖励来源需要另行核查，不是正确答案。</p><p v-if="disagreement">同题、同准则最近两轮有 {{disagreement.changed}} / {{disagreement.total}} 个回答对顺序改变。</p><p>已记录 {{rounds.length}} 轮；这是当前页面的评价轮次，不是人数。</p><button :disabled="!rounds.length" @click="downloadSearch({kind:'learner-preference-review',source,provenance:meta,items:data.items,rounds},'preference-reviews.json')">导出评价记录</button><div class="controls"><button v-for="(s,i) in stages" :key="s.name" :aria-pressed="flow===i" @click="flow=i">{{s.name}}</button></div><p>{{stages[flow].detail}}</p><p class="note">盲评是界面隐藏来源，不是安全隔离；阅读原文件或来源文本可能破盲。没有实际奖励模型就不填分数，读者偏好也不自动变成训练结果。</p></section></template>
<style scoped>.response{padding:16px;margin:12px 0;border:1px solid #cbd5e1;border-radius:10px}.response p{white-space:pre-wrap}</style>
