<script setup lang="ts">
import {computed,ref,shallowRef,watch} from 'vue'
import cases from '../../../../backend/reasoning_cases.json'
import TraceLoader from './TraceLoader.vue'
import ReasoningGroupLegacy from './ReasoningGroupLegacy.vue'
import LanguageModelStatus from './LanguageModelStatus.vue'
import {useLocalLanguage,downloadLanguageRecord} from '../../papers/useLocalLanguage'
import {parseGroup,rewardStats} from '../../papers/trainingTraces'
import {envelope} from '../../papers/traceValidation'
const taskIds=ref(cases.tasks.map(t=>t.id)),samples=ref(4),seed=ref(7),temperature=ref(.8),index=ref(0),selected=ref(0),meta=ref(''),simulation=ref([1,0,1,0])
const data=shallowRef<ReturnType<typeof parseGroup>|null>(null)
const local=useLocalLanguage('24','training'),{config,busy,error}=local
const current=computed(()=>data.value?.tasks[index.value]),rewards=computed(()=>current.value?.answers.map(a=>a.answer===current.value!.expected?1:0)??[]),stats=computed(()=>rewardStats(rewards.value)),demo=computed(()=>rewardStats(simulation.value))
function clear(){local.invalidate();data.value=null;meta.value='';index.value=0;selected.value=0}
watch([taskIds,samples,seed,temperature],clear,{deep:true,flush:'sync'})
function accept(v:unknown){data.value=parseGroup(v);index.value=0;selected.value=0;meta.value='导入来源由提供者声明'}
function receive(v:unknown){const e=envelope(v,'24');accept(e.data);meta.value=JSON.stringify(e.provenance,null,2)}
function start(){clear();local.request({paper_id:'24',task_ids:taskIds.value,samples:samples.value,seed:seed.value,temperature:temperature.value,max_new_tokens:64},receive)}
const duplicateCount=computed(()=>current.value?current.value.answers.length-new Set(current.value.answers.map(a=>a.output)).size:0)
</script>
<template><section class="paper-lab"><h3>同题同分时，优势还剩什么？</h3><details open><summary>先拨动奖励开关（纯数学算例，不是模型回答）</summary><div class="controls"><button v-for="(r,i) in simulation" :key="i" @click="simulation[i]=1-r">r{{i+1}}={{r}}</button><button @click="simulation=[0,0,0,0]">全部0</button><button @click="simulation=[1,1,1,1]">全部1</button></div><p>均值 {{demo.mean.toFixed(3)}}；总体标准差 {{demo.std.toFixed(3)}}；优势 {{demo.advantages.map(a=>a.toFixed(3)).join(' / ')}}。</p></details><h4>再检查实际回答</h4><div class="controls"><label v-for="t in cases.tasks" :key="t.id"><input v-model="taskIds" type="checkbox" :value="t.id">{{t.category}}</label><label>每题候选<select v-model.number="samples"><option :value="2">2</option><option :value="4">4</option><option :value="8">8</option></select></label><label>seed<input v-model.number="seed" type="number" min="0" max="1000000"></label><label>温度 {{temperature}}<input v-model.number="temperature" type="range" min="0.1" max="2" step="0.1"></label></div><button :disabled="busy||!config?.configured||!taskIds.length" @click="start">采样候选（GPT‑2替代，每条最多64 token）</button><LanguageModelStatus guide="TRAINING_CATEGORY.md" :config="config" :busy="busy" :error="error" @refresh="local.refresh" @cancel="local.cancel"/><TraceLoader paper-id="24" :validate="parseGroup" @loaded="accept" @clear="clear"/>
<template v-if="data&&current"><p>记录路线 {{data.route}}；不会因选择本课就变成R1模型。</p><select v-model.number="index" @change="selected=0"><option v-for="(t,i) in data.tasks" :key="t.id" :value="i">{{t.id}} · {{t.category}}</option></select><h4>{{current.question}}</h4><table><thead><tr><th>候选</th><th>提取答案</th><th>r</th><th>组内优势</th><th>实际输出token</th></tr></thead><tbody><tr v-for="(a,i) in current.answers" :key="i"><td><button @click="selected=i">{{i+1}}</button></td><td>{{a.answer??'格式失败'}}</td><td>{{rewards[i]}}</td><td><span class="adv" :style="{width:`${Math.abs(stats.advantages[i])*35}px`,background:stats.advantages[i]>=0?'#86efac':'#fca5a5'}"/> {{stats.advantages[i].toFixed(4)}}</td><td>{{a.generated.length}}</td></tr></tbody></table><p>目标 {{current.expected}}；mean={{stats.mean.toFixed(4)}}；std={{stats.std.toFixed(4)}}。A=(r−mean)/std，零方差按本课约定置0，不产生NaN。</p><p>重复输出 {{duplicateCount}} 条：仍作为实际采样保留，不为了凑多样性改写回答。</p><pre>{{current.answers[selected].output||'（空输出）'}}</pre><details><summary>此候选实际输入、停止原因与token记录</summary><pre>{{current.answers[selected].text}}</pre><p>{{current.answers[selected].stop_reason}}</p><pre>{{current.answers[selected].generated}}</pre></details><table><thead><tr><th>题目</th><th>成功候选/采样数</th><th>平均输出token</th></tr></thead><tbody><tr v-for="t in data.tasks" :key="t.id"><td>{{t.id}}</td><td>{{t.answers.filter(a=>a.answer===t.expected).length}} / {{t.answers.length}}</td><td>{{(t.answers.reduce((s,a)=>s+a.generated.length,0)/t.answers.length).toFixed(1)}}</td></tr></tbody></table><button v-if="local.trace.value" @click="downloadLanguageRecord(local.trace.value,'24')">导出实际采样记录</button><details><summary>来源和采样参数</summary><pre>{{meta}}</pre></details></template><details><summary>旧版单题记录</summary><ReasoningGroupLegacy/></details><p class="note">这里只计算整数答案奖励与组内标准化，没有比率、裁剪、KL或训练。不给长回答额外奖励，候选成功比例不当作原文pass@1或self-consistency。R1-Zero与R1的训练路线仍需结合原文分别阅读。</p></section></template>
<style scoped>.adv{display:inline-block;height:10px;max-width:130px}</style>
