<script setup lang="ts">
import {computed,ref,shallowRef} from 'vue'
import TraceLoader from './TraceLoader.vue'
import TicSampleLab from './TicSampleLab.vue'
import SelfPlayLegacy from './SelfPlayLegacy.vue'
import {parseSelfPlay} from '../../papers/searchTraces'
import {ticWinner} from '../../papers/boardRules'
import {downloadSearch} from '../../papers/ticSearch'
import {research} from '../../papers/research'
import type {envelope} from '../../papers/traceValidation'
const provenance=shallowRef<ReturnType<typeof envelope>['provenance']|null>(null)
const data=shallowRef<ReturnType<typeof parseSelfPlay>|null>(null),gameIndex=ref(0),step=ref(0),checkpoint=ref(0),showOutcome=ref(false),task=ref(0)
const game=computed(()=>data.value?.games[gameIndex.value]),sample=computed(()=>game.value?.steps[step.value])
const board=computed(()=>{const b=Array<number>(9).fill(0);game.value?.steps.slice(0,step.value).forEach((s,i)=>b[s.move]=i%2+1);return b})
const finalBoard=computed(()=>{const b=Array<number>(9).fill(0);game.value?.steps.forEach((s,i)=>b[s.move]=i%2+1);return b})
const winner=computed(()=>ticWinner(finalBoard.value)),z=computed(()=>winner.value===0?0:winner.value===step.value%2+1?1:-1)
const loss=computed(()=>{if(!sample.value)return null;const s=sample.value;const policy=s.pi.reduce<number>((sum,p,i)=>p===0?sum:s.policy[i]===0?Infinity:sum-p*Math.log(s.policy[i]),0);return {policy,value:(z.value-s.value)**2}})
const cp=computed(()=>data.value?.checkpoints[checkpoint.value])
const evaluationComparable=computed(()=>{const all=data.value?.checkpoints??[];return all.every(c=>c.evaluation.opponent_revision===all[0].evaluation.opponent_revision&&c.evaluation.protocol_hash===all[0].evaluation.protocol_hash)})
const evidence=research['03'].experiments[0]
function accept(v:unknown){data.value=parseSelfPlay(v);gameIndex.value=0;step.value=0;checkpoint.value=0;showOutcome.value=false}
function changeGame(){step.value=0;showOutcome.value=false}
function exportSample(){if(!sample.value||!data.value||!game.value)return;downloadSearch({kind:'derived-training-sample-from-import',paper_id:'03',provenance:provenance.value,checkpoint_revision:game.value.checkpoint_revision,game_id:game.value.id,seed:game.value.seed,state:board.value,to_play:step.value%2+1,pi:sample.value.pi,z:z.value,source:'derived from user-supplied archive; authenticity not verified'},'selfplay-training-sample.json')}
</script>
<template><section class="paper-lab"><h3>AlphaZero：搜索的答案，怎样成为下一轮的教材？</h3><TicSampleLab/><h4>真实训练成长档案</h4><p>要比较“学习前后”，必须导入实际检查点和对局。下面不使用规则搜索样本伪装已训练网络。</p><TraceLoader paper-id="03" :validate="parseSelfPlay" @loaded="accept" @provenance="provenance=$event" @clear="data=null;provenance=null"/>
<template v-if="data&&game"><label>真实自我对弈<select v-model.number="gameIndex" @change="changeGame"><option v-for="(g,i) in data.games" :key="g.id" :value="i">{{g.id}} · {{g.checkpoint_revision}}</option></select></label><label>已落 {{step}} 手<input v-model.number="step" type="range" min="0" :max="game.steps.length"></label><div class="controls"><button :disabled="step===0" @click="step--">上一步</button><button :disabled="step===game.steps.length" @click="step++">下一步</button><button @click="showOutcome=!showOutcome">{{showOutcome?'隐藏终局标签':'揭示终局和 z'}}</button></div><div class="cards"><article><div class="ttt"><span v-for="(s,i) in board" :key="i" :class="{next:sample?.move===i}">{{s===1?'X':s===2?'O':i}}</span></div><p>{{sample?`落子前，轮到 ${step%2===0?'X':'O'}；蓝格是记录中的下一手`:'完整终局，不再生成训练状态'}}</p><p v-if="showOutcome">终局{{winner===0?'平局':winner===1?'X胜':'O胜'}}<template v-if="sample">；此样本当前方 z={{z}}</template>。</p></article><article v-if="sample"><table><thead><tr><th>落点</th><th>网络 p</th><th>搜索 N</th><th>监督 π</th></tr></thead><tbody><tr v-for="(p,i) in sample.policy" :key="i"><td>{{i}}</td><td>{{p.toFixed(4)}}</td><td>{{sample.visits[i]}}</td><td><meter min="0" max="1" :value="sample.pi[i]"/> {{sample.pi[i].toFixed(4)}}</td></tr></tbody></table><p>π由 N^(1/τ) 归一化校验，τ={{sample.temperature}}；不是网络 p 的另一个名字。</p></article></div><template v-if="showOutcome&&sample&&loss"><h4>把这一个样本代入损失</h4><p>(z−v)²={{loss.value.toFixed(5)}}；−Σπ log p={{Number.isFinite(loss.policy)?loss.policy.toFixed(5):'∞（π>0 的位置 p=0）'}}。</p><p>记录 v={{sample.value.toFixed(4)}}，视角是落子前当前行动方。这只是前向损失分解，未加权重正则项，也没有反向传播或参数更新。</p><button @click="exportSample">导出此 (s,π,z) 样本</button></template>
<h4>回到同一个空棋盘，比较检查点</h4><label>训练时间轴<input v-model.number="checkpoint" type="range" min="0" :max="data.checkpoints.length-1"></label><template v-if="cp"><p>{{cp.name}} · step {{cp.training_step}} · revision {{cp.revision}}；下图始终为空棋盘，不是上方当前对局。</p><div class="policy-board"><article v-for="(p,i) in cp.policy" :key="i" :style="{background:`rgba(37,99,235,${0.05+0.65*p})`}"><b>{{i}}</b><span>p {{p.toFixed(3)}}</span><span>N {{cp.visits[i]}}</span></article></div><p>空棋盘网络 v={{cp.value}}。策略变化只能说明输出改变，棋力需要固定对手检验。</p></template><p v-if="!evaluationComparable" class="alert">这些检查点的对手版本或评估协议不同，不能据下表归因于训练进步。</p><table><thead><tr><th>检查点</th><th>胜 / 平 / 负</th><th>胜率（不含半个平局）</th><th>对手 / 协议</th></tr></thead><tbody><tr v-for="c in data.checkpoints" :key="c.revision"><td>{{c.name}}</td><td>{{c.evaluation.wins}} / {{c.evaluation.draws}} / {{c.evaluation.losses}}</td><td>{{(100*c.evaluation.wins/(c.evaluation.wins+c.evaluation.draws+c.evaluation.losses)).toFixed(1)}}%</td><td>{{c.evaluation.opponent_revision}} / {{c.evaluation.protocol_hash}}</td></tr></tbody></table><p class="note">只比较同协议的记录声明，不验证训练来源真实性。胜率分母包括平局；单次有限局数的结果不是稳定棋力证明。</p></template>
<h4>原文对照：没有输，是否每局都赢？</h4><label>原论文任务<select v-model.number="task"><option v-for="(r,i) in evidence.rows" :key="r.name" :value="i">{{r.name}}</option></select></label><div class="outcomes" aria-label="原文胜平负比例"><span v-for="(n,i) in evidence.rows[task].values" :key="i" :style="{flex:n,background:['#bbf7d0','#e2e8f0','#fecaca'][i]}" v-show="n">{{['胜','平','负'][i]}} {{n}}</span></div><p>{{evidence.setup}} 来源 {{evidence.source.label}}，页 {{evidence.source.pages.join('、')}}。这是2017版特定对手与时间条件，不拿井字棋结果代替它。</p><details><summary>旧版单盘档案（缺访问数来源与控制字段）</summary><SelfPlayLegacy/></details></section></template>
<style scoped>.ttt{display:grid;grid-template-columns:repeat(3,64px);width:192px}.ttt span{height:64px;display:grid;place-items:center;border:1px solid #94a3b8;font-size:25px}.next{background:#dbeafe}.policy-board{display:grid;grid-template-columns:repeat(3,100px);gap:5px}.policy-board article{padding:10px;display:grid;font-size:12px}.outcomes{display:flex;min-height:40px;margin:20px 0}.outcomes span{display:grid;place-items:center;min-width:32px;font-size:12px}</style>
