<script setup lang="ts">
import { computed,ref,shallowRef,watch } from 'vue'
import TraceLoader from './TraceLoader.vue'
import TransferReplay from './TransferReplay.vue'
import { research } from '../../papers/research'
import { parseTransfer,paired } from '../../papers/transferTraces'
const evidence=research['05'].experiments[0],task=ref(0),revealed=ref(false),guess=ref('')
const data=shallowRef<ReturnType<typeof parseTransfer>|null>(null),budget=ref(0),seed=ref(0),step=ref(0)
const budgets=computed(()=>[...new Set(data.value?.runs.map(r=>r.label_budget)??[])].sort((a,b)=>a-b))
const seeds=computed(()=>[...new Set(data.value?.runs.filter(r=>r.label_budget===budget.value).map(r=>r.seed)??[])].sort((a,b)=>a-b))
const runs=computed(()=>data.value?.runs.filter(r=>r.label_budget===budget.value&&r.seed===seed.value)??[])
const steps=computed(()=>[...new Set(runs.value.flatMap(r=>r.points.map(p=>p.step)))].sort((a,b)=>a-b))
const matched=computed(()=>paired(runs.value.find(r=>r.condition==='random'),runs.value.find(r=>r.condition==='pretrained')))
const axis=computed(()=>{const ps=runs.value.flatMap(r=>r.points);return {xmin:Math.min(...ps.map(p=>p.step)),xmax:Math.max(...ps.map(p=>p.step)),ymin:Math.min(...ps.map(p=>p.value)),ymax:Math.max(...ps.map(p=>p.value))}})
function x(n:number){return 65+(n-axis.value.xmin)/(axis.value.xmax-axis.value.xmin||1)*540}
function y(n:number){return 245-(n-axis.value.ymin)/(axis.value.ymax-axis.value.ymin||1)*205}
const differences=computed(()=>{if(!data.value)return [];const all=data.value.runs;return seeds.value.flatMap(s=>{const a=all.find(r=>r.seed===s&&r.label_budget===budget.value&&r.condition==='random'),b=all.find(r=>r.seed===s&&r.label_budget===budget.value&&r.condition==='pretrained');if(!paired(a,b))return [];const p=a!.points.find(p=>p.step===step.value),q=b!.points.find(p=>p.step===step.value);return p&&q?[{seed:s,delta:(q.value-p.value)*(data.value!.direction==='up'?1:-1)}]:[]})})
const mean=computed(()=>differences.value.reduce<number>((s,d)=>s+d.delta,0)/(differences.value.length||1))
watch(budget,()=>{seed.value=seeds.value[0]??0});watch([budget,seed],()=>{step.value=steps.value[0]??0})
watch(task,()=>{revealed.value=false;guess.value=''})
function accept(v:unknown){data.value=parseTransfer(v);budget.value=budgets.value[0];seed.value=seeds.value[0];step.value=steps.value[0]}
</script>
<template><section class="paper-lab"><h3>先问“什么变了”，再看分数</h3><p>GPT‑1 研究预训练后再用标签微调。下面先比较已核查的原文 Table 5，再查看你自己的成对训练记录；两类证据分开。</p><label>原文指标<select v-model.number="task"><option :value="0">异质任务 Avg</option><option :value="1">QNLI accuracy</option></select></label><label>预测：去掉辅助 LM 是否会变差？<input v-model="guess" maxlength="150"></label><button @click="revealed=true">揭示原文消融</button><template v-if="revealed"><div v-for="r in evidence.rows" :key="r.name" class="evidence-row"><span>{{r.name}}</span><meter min="0" max="100" :value="r.values[task]"/><b>{{r.values[task]}}{{task===1?'%':' 分'}}</b></div><p>无辅助 LM − 完整方法 = {{(evidence.rows[3].values[task]-evidence.rows[2].values[task]).toFixed(1)}} {{task===1?'个百分点':'分'}}。切换指标再看一次：变化方向是否相同？</p><p class="note">{{evidence.source.label}}；原文页 {{evidence.source.pages.join('、')}}。这组消融不是标签预算扫描，不能画成不同标签量下的训练曲线。</p></template>
<h4>用成对记录检验少标签迁移</h4><p>需要同一架构、划分、标签子集、优化设置、总训练步数的 random/pretrained 配对；支持在每个观测点附带当时的错例。没有文件时这里不显示曲线。</p><TraceLoader paper-id="05" :validate="parseTransfer" @loaded="accept" @clear="data=null"/>
<template v-if="data"><details><summary>配对控制条件与指标</summary><p>{{data.architecture}}；指标 {{data.metric}}（{{data.unit}}，{{data.direction==='up'?'越高越好':'越低越好'}}）；划分 {{data.split_hash}}；预训练来源 {{data.pretraining_source}}</p><pre v-for="r in runs" :key="r.condition">{{r.condition}} · 标签子集 {{r.label_subset_hash}} · 优化设置 {{r.optimizer_hash}} · 总步数 {{r.train_steps}}</pre></details><div class="controls"><label>实际标签预算<select v-model.number="budget"><option v-for="b in budgets" :key="b" :value="b">{{b}}</option></select></label><label>seed<select v-model.number="seed"><option v-for="s in seeds" :key="s" :value="s">{{s}}</option></select></label><label>实际观测 step<select v-model.number="step"><option v-for="s in steps" :key="s" :value="s">{{s}}</option></select></label></div><p v-if="!matched" class="alert">此组合缺少配对或控制条件不一致，只能查看记录，不能计算预训练收益。</p><svg v-if="runs.length" viewBox="0 0 660 305" role="img" aria-label="训练观测点：橙色随机初始化，蓝色预训练"><path d="M60 20V250H620" fill="none" stroke="#64748b"/><text x="62" y="275">{{axis.xmin}}</text><text x="560" y="275">{{axis.xmax}} step</text><text x="0" y="42">{{axis.ymax.toPrecision(4)}}</text><text x="0" y="245">{{axis.ymin.toPrecision(4)}}</text><g v-for="r in runs" :key="r.condition" :fill="r.condition==='random'?'#ea580c':'#2563eb'"><polyline :points="r.points.map(p=>`${x(p.step)},${y(p.value)}`).join(' ')" fill="none" :stroke="r.condition==='random'?'#ea580c':'#2563eb'" stroke-dasharray="3 5"/><circle v-for="p in r.points" :key="p.step" :cx="x(p.step)" :cy="y(p.value)" :r="p.step===step?7:4" tabindex="0" role="button" :aria-label="`${r.condition} step ${p.step} 值 ${p.value}`" @click="step=p.step" @keydown.enter="step=p.step"><title>{{r.condition}} · {{p.step}} · {{p.value}}</title></circle></g></svg><p class="note">橙：random；蓝：pretrained。纵轴自动缩放。虚线仅连接观测点；不插值或宣称中间步数有观测。</p><div class="cards"><article v-for="r in runs" :key="r.condition"><h4>{{r.condition}} · step {{step}}</h4><template v-if="r.points.some(p=>p.step===step)"><p>{{data.metric}} = {{r.points.find(p=>p.step===step)?.value}}</p><ul><li v-for="(e,i) in r.points.find(p=>p.step===step)?.errors" :key="i">{{e.input}} → {{e.predicted}}（目标 {{e.expected}}）</li></ul><p v-if="!r.points.find(p=>p.step===step)?.errors.length">此点未附错例；不等于没有错误。</p></template><p v-else>此步没有观测，不能拿相邻步补齐。</p></article></div><h4>在同预算、同 step 跨 seed 看配对差值</h4><p v-if="differences.length">{{differences.length}} 个有效配对；平均改善 {{mean.toPrecision(4)}} {{data.unit}}。正值=按该指标方向改善。</p><p v-else>没有满足控制条件且同一步数的配对。</p><ul><li v-for="d in differences" :key="d.seed">seed {{d.seed}}：{{d.delta.toPrecision(4)}}</li></ul><p class="note">列出各次差值而不制造误差条；即使均值为正，小样本也不能证明稳定优势。哈希和控制信息是记录者声明，页面无法验证其真实训练过程。</p></template><details><summary>旧版记录查看（控制字段不足，不纳入配对统计）</summary><TransferReplay/></details></section></template>
<style scoped>.evidence-row{display:flex;flex-wrap:wrap;gap:12px;align-items:center;margin:14px 0}.evidence-row span{min-width:240px}.evidence-row meter{width:180px}circle{cursor:pointer}svg text{font-size:11px}</style>
