<script setup lang="ts">
import { computed,ref,shallowRef } from 'vue'
import TraceLoader from './TraceLoader.vue'
import { fields,list,text,integer,number,choice } from '../../papers/traceValidation'
import { research } from '../../papers/research'
const schema=fields({metric:text,split_hash:text,runs:list(fields({condition:choice('random','pretrained'),seed:integer,label_budget:integer,points:list(fields({step:integer,value:number}),2,1000),errors:list(fields({input:text,expected:text,predicted:text}),0,100)}),2,100)})
function parse(v:unknown){const d=schema(v),keys=new Set<string>();for(const r of d.runs){const key=`${r.condition}/${r.seed}/${r.label_budget}`;if(keys.has(key))throw Error('同条件、seed、标签预算重复');keys.add(key);if(r.points.some((p,i)=>i>0&&p.step<=r.points[i-1].step))throw Error('训练步数需严格递增')}return d}
const data=shallowRef<ReturnType<typeof parse>|null>(null),budget=ref(0),seed=ref(0),selected=ref(0)
const budgets=computed(()=>[...new Set(data.value?.runs.map(r=>r.label_budget)??[])].sort((a,b)=>a-b))
const seeds=computed(()=>[...new Set(data.value?.runs.map(r=>r.seed)??[])].sort((a,b)=>a-b))
const runs=computed(()=>data.value?.runs.filter(r=>r.label_budget===budget.value&&r.seed===seed.value)??[])
const plot=computed(()=>{const ps=runs.value.flatMap(r=>r.points);if(!ps.length)return [];const xmin=Math.min(...ps.map(p=>p.step)),xmax=Math.max(...ps.map(p=>p.step)),ymin=Math.min(...ps.map(p=>p.value)),ymax=Math.max(...ps.map(p=>p.value));return runs.value.map(r=>({condition:r.condition,path:r.points.map(p=>`${50+(p.step-xmin)/(xmax-xmin||1)*560},${270-(p.value-ymin)/(ymax-ymin||1)*230}`).join(' ')}))})
function accept(v:unknown){data.value=parse(v);budget.value=budgets.value[0];seed.value=seeds.value[0];selected.value=0}
</script>
<template><section class="paper-lab"><h3>标注很少时，预训练是否改变学习过程？</h3><p>先看原文任务消融；再导入同划分、同标签预算下的真实训练曲线。没有训练记录时不制造一条“预训练更好”的曲线。</p><div class="cards"><article v-for="r in research['05'].experiments[0].rows" :key="r.name"><strong>{{r.name}}</strong><p>Avg {{r.values[0]}}；QNLI {{r.values[1]}}%</p></article></div><TraceLoader paper-id="05" :validate="parse" @loaded="accept" @clear="data=null"/><template v-if="data"><div class="controls"><label>真实标签预算<select v-model.number="budget" @change="selected=0"><option v-for="b in budgets" :key="b" :value="b">{{b}}</option></select></label><label>seed<select v-model.number="seed" @change="selected=0"><option v-for="s in seeds" :key="s" :value="s">{{s}}</option></select></label></div><p>指标 {{data.metric}}；同一划分声明 {{data.split_hash}}。横轴 step，纵轴观测值自动缩放，不代表从零开始。</p><svg v-if="runs.length" viewBox="0 0 660 310"><path d="M45 20V280H625" stroke="#64748b" fill="none"/><polyline v-for="r in plot" :key="r.condition" :points="r.path" fill="none" :stroke="r.condition==='random'?'#ea580c':'#2563eb'" stroke-width="3"/></svg><p v-else>该预算与 seed 组合没有记录，不插值。</p><p>橙：随机初始化；蓝：预训练。单个 seed 不能证明稳定优势。</p><div v-for="(r,i) in runs" :key="i"><button @click="selected=i">查看 {{r.condition}} 错例</button><ul v-if="selected===i"><li v-for="(e,j) in r.errors" :key="j">{{e.input}} → {{e.predicted}}（目标 {{e.expected}}）</li></ul></div></template><p class="note">Avg 是异质任务分数均值，不是统一分类准确率；去掉辅助 LM 的效果并非所有任务同向。当前不训练，记录的划分哈希与控制条件需独立核验。</p></section></template>
