import type { Paper } from './types'
// 页码指本地 PDF 从 1 开始的页面编号，不是 PDF 内可能不同的印刷页码。
export const papers: Paper[] = [
 {id:'01',name:'ResNet',year:2015,group:'视觉与结构',title:'Deep Residual Learning for Image Recognition',file:'01_resnet.pdf',folder:'ai-papers-01',pages:[2,3],section:'Figure 2 · §3.1–3.2',question:'为什么加回输入，深层网络会更容易学习？',principle:'学习 F(x)=H(x)−x，再计算 F(x)+x。维度不同用投影捷径 Ws；原版基本块在相加后再 ReLU。',limitation:'小实验是固定卷积核的单块前向，不证明训练收益，也不代表完整 ResNet-152。',exercise:'先把主分支强度调到 0，再开关捷径。比较输出与输入；注意负值会被最终 ReLU 截断。',dependencies:[],quiz:{question:'残差相加对通道数有什么影响？',options:['通道翻倍','两路形状对齐后相加，通道数不变','自动降为一个通道'],answer:1,explanation:'这是逐元素加法，不是拼接。形状变化时须先做投影。'}},
 {id:'02',name:'AlphaGo',year:2016,group:'搜索与强化学习',title:'Mastering the game of Go with deep neural networks and tree search',file:'02_alphago.pdf',folder:'ai-papers-01',pages:[1,3],section:'Figure 3 · Monte Carlo tree search',question:'策略、价值和搜索如何共同决定落子？',principle:'策略提供行动先验，搜索兼顾行动价值与探索；叶子评估结合价值网络与快速 rollout，结果回传到树中。',limitation:'展示三个候选行动的根节点统计，不实现围棋规则、多层搜索、训练或原系统全部细节。叶子回报是固定教学输入。',exercise:'调节探索强度与搜索次数，比较先验最高的行动是否一定访问最多；再改变价值与 rollout 混合比例。',dependencies:['01'],quiz:{question:'原版 AlphaGo 搜索的叶子评估包括什么？',options:['仅看策略概率','价值网络与快速 rollout 的组合','只随机选一个动作'],answer:1,explanation:'2016 年 AlphaGo 与后来的 AlphaZero 不能混为一谈。'}},
 {id:'03',name:'AlphaZero',year:2017,group:'搜索与强化学习',title:'Mastering Chess and Shogi by Self-Play with a General Reinforcement Learning Algorithm',file:'03_alphazero.pdf',folder:'ai-papers-01',pages:[2,3],section:'Equation 1 · Self-play and search',question:'搜索怎样反过来成为网络的老师？',principle:'同一网络输出策略 p 与价值 v；MCTS 访问次数形成目标 π，自我对弈的终局结果 z 监督价值。',limitation:'仅模拟根节点搜索及损失计算，不执行完整自我对弈或梯度更新；不假装是可下棋的 AlphaZero。',exercise:'增加搜索次数，观察 π 与原始 p 的差别，再改变终局 z 看价值损失。',dependencies:['02'],quiz:{question:'策略训练目标 π 从哪里来？',options:['网络的原始输出直接复制','搜索得到的访问统计','人工标注每一步棋'],answer:1,explanation:'搜索改善行动分布，网络再拟合搜索分布；终局结果监督价值。'}},
 {id:'04',name:'Transformer',year:2017,group:'语言与注意力',title:'Attention Is All You Need',file:'04_transformer.pdf',folder:'ai-papers-01',pages:[3,4],section:'Figure 1–2 · §3.1–3.2',question:'Decoder 如何读取 Encoder 的输出？',principle:'自注意力在同一序列内部交换信息；交叉注意力以 Decoder 表示为 Q、Encoder 表示为 K/V。原论文采用 Post-LN。',limitation:'本页展示小型交叉注意力，不是完整翻译器；已有详细 Transformer 页另有 23 节点自注意力实验。',exercise:'改变源序列某个词元，观察 K/V 与目标输出变化；比较源长 3、目标长 2 时关系表为何是 2×3。',dependencies:['01'],quiz:{question:'交叉注意力的关系表最后两维是？',options:['目标长度 × 源长度','隐藏维度 × 隐藏维度','源长度 × 词表大小'],answer:0,explanation:'每个目标 Query 对所有源 Key 计算分数。'}},
 {id:'05',name:'GPT-1',year:2018,group:'语言与注意力',title:'Improving Language Understanding by Generative Pre-Training',file:'05_gpt-1.pdf',folder:'ai-papers-01',pages:[3],section:'§3 · Equations 1–5',question:'同一个语言模型怎样迁移到分类任务？',principle:'先用无标注文本做自回归预训练，再加任务输出层并监督微调；论文也使用辅助语言建模目标。',limitation:'只有固定小模型前向与任务头切换，没有预训练、微调或实际语言理解能力。',exercise:'切换语言建模与句子分类头，看同一个隐藏表示如何产生 [T,V] 或 [1,K]。',dependencies:['04'],quiz:{question:'原始 GPT-1 的主要迁移方式是什么？',options:['只给提示，不更新参数','预训练后进行任务监督微调','完全不需要文本'],answer:1,explanation:'不要把 GPT-3 的 few-shot 设置倒推到 GPT-1。'}},
 {id:'06',name:'BERT',year:2018,group:'语言与注意力',title:'BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding',file:'06_bert.pdf',folder:'ai-papers-01',pages:[4],section:'§3.1 · Masked LM and Next Sentence Prediction',question:'遮住一个词，为什么仍能看两侧上下文？',principle:'[MASK] 是输入词元，仍参与双向注意力；MLM 只在选中的预测位置计算损失。原论文还有 NSP 任务。',limitation:'为清楚演示，手动只遮住一个词；原论文选择 15% 位置，并采用 80% MASK、10% 随机词、10% 保持不变的策略。本例不训练 NSP。',exercise:'移动遮挡位置，观察注意力表仍不是下三角；比较预测位置的 loss 与其他位置。',dependencies:['04'],quiz:{question:'把一个词换成 [MASK] 是否意味着屏蔽其注意力列？',options:['是，两者相同','不是，[MASK] 仍是有效词元','意味着删除该位置'],answer:1,explanation:'MLM 替换输入与 padding/causal attention mask 是不同操作。'}},
 {id:'07',name:'GPT-2',year:2019,group:'语言与注意力',title:'Language Models are Unsupervised Multitask Learners',file:'07_gpt-2.pdf',folder:'ai-papers-01',pages:[1,2,3],section:'§2 · Approach',question:'任务描述如何成为模型的上下文？',principle:'任务、输入、输出可串为一个符号序列，语言建模让模型在不同文本任务之间迁移；论文研究 zero-shot 表现。',limitation:'固定教学词表与权重只展示提示影响数据流，不会实际翻译，也不复现 GPT-2 的规模、分词与能力。',exercise:'开关任务前缀，观察序列长度、因果关系表和最后位置分布。',dependencies:['05'],quiz:{question:'zero-shot 意味着模型没有训练过吗？',options:['是','不是，通常指当前评测不提供该任务示例或额外微调','意味着输入为空'],answer:1,explanation:'模型已经经历大规模预训练；zero-shot 是任务设置。'}},
 {id:'08',name:'GPT-3',year:2020,group:'语言与注意力',title:'Language Models are Few-Shot Learners',file:'08_gpt-3.pdf',folder:'ai-papers-01',pages:[3,4],section:'Figure 1.1 · In-context learning',question:'示例放进上下文，为什么不等于微调？',principle:'few-shot 把若干任务示例和问题一起输入；论文评测时不通过梯度更新权重适应这些示例。',limitation:'示例以离散教学 token 表达。概率来自未训练小网络，不能用它证明示例越多效果必然越好。',exercise:'选择 0、1、2 个示例，观察 token 数和注意力单元数如何变化，权重矩阵保持不变。',dependencies:['07'],quiz:{question:'本页增加 few-shot 示例改变了什么？',options:['输入序列','已训练权重','优化器状态'],answer:0,explanation:'上下文学习发生在前向过程中，区别于带梯度的微调。'}},
 {id:'09',name:'Scaling Laws',year:2020,group:'规模与计算',title:'Scaling Laws for Neural Language Models',file:'09_scaling-laws-kaplan.pdf',folder:'ai-papers-01',pages:[1,3],section:'§1.1 · Power laws',question:'模型、数据与算力为什么要一起看？',principle:'论文观察语言模型交叉熵对参数量、数据量与计算量的经验幂律关系，强调其他因素不成为瓶颈的条件。',limitation:'这里的常数与归一化单位是教学设定，不是原论文拟合值，不用于预测真实模型分数或采购算力。',exercise:'分别增大模型和数据，观察单一方向扩展如何遇到另一项的瓶颈。',dependencies:['05'],quiz:{question:'规模规律是数学保证吗？',options:['是，适用于所有模型和数据','不是，是特定实验条件下的经验关系','说明数据不重要'],answer:1,explanation:'分布、训练设置和外推范围都会影响结论。'}},
 {id:'10',name:'ViT',year:2020,group:'视觉与结构',title:'An Image is Worth 16x16 Words: Transformers for Image Recognition at Scale',file:'10_vit.pdf',folder:'ai-papers-01',pages:[3],section:'Figure 1 · §3.1',question:'二维图片怎样变成 Transformer 的 token？',principle:'切成固定 patch、展平、线性投影，加入 class token 与位置嵌入，再送入 Transformer Encoder。',limitation:'使用 6×6 单通道图、4 维嵌入和一个固定注意力层；不是预训练 ViT，不具备图片分类能力。',exercise:'在输入网格点击像素，切换 patch 边长 2/3，比较 N=HW/P² 与 N×N 注意力矩阵。',dependencies:['04'],quiz:{question:'patch 变小而图片大小不变，会怎样？',options:['token 更少','token 更多，注意力关系表通常更大','token 数不变'],answer:1,explanation:'patch 数与 1/P² 成正比，自注意力表的单元数随 N² 增长。'}},
 {id:'11',name:'DDPM',year:2020,group:'扩散与生成',title:'Denoising Diffusion Probabilistic Models',file:'11_ddpm.pdf',folder:'ai-papers-02',pages:[2,4],section:'Equation 4 · Algorithm 1–2',question:'加噪与学习去噪分别在做什么？',principle:'正向过程按预定方差日程加高斯噪声，模型学习预测噪声，反向采样逐步生成图像。',limitation:'本例能知道原始噪声，只能演示理想估计及人为误差；没有训练噪声预测网络，不能把重建当作真实生成。',exercise:'增大时间步，再增加噪声预测误差，看 x₀ 重建为什么在强噪声下更敏感。',dependencies:['01'],quiz:{question:'实际生成时能直接获得真实噪声 ε 吗？',options:['总是能','不能，要由已训练网络估计','可以从图像文件名得到'],answer:1,explanation:'本页为手算展示保留了 ε，实际反向生成没有这个答案。'}},
 {id:'12',name:'CLIP',year:2021,group:'多模态',title:'Learning Transferable Visual Models From Natural Language Supervision',file:'12_clip.pdf',folder:'ai-papers-02',pages:[2,5],section:'Figure 1 · Figure 3 pseudocode',question:'图片与文字怎样被放到同一个空间？',principle:'两个编码器的特征经投影与 L2 归一化，构造批内图文相似度矩阵，用双向对比目标提高正确配对的分数。',limitation:'使用手工图文向量，跳过真实编码器训练。余弦相似度不是天然校准过的类别置信度。',exercise:'交换两个文本向量而保持配对标签不变，观察对角线和双向损失；调节温度看概率尖锐程度。',dependencies:['10'],quiz:{question:'批大小 N 的 CLIP 配对矩阵形状？',options:['N×N','N×词表大小','仅一个标量'],answer:0,explanation:'每张图片要与批次中的每段文字比较。'}},
 {id:'13',name:'InstructGPT',year:2022,group:'搜索与强化学习',title:'Training language models to follow instructions with human feedback',file:'13_instructgpt.pdf',folder:'ai-papers-02',pages:[3,6],section:'Figure 2 · §3.1',question:'人类偏好怎样成为模型优化信号？',principle:'SFT 示范、偏好比较训练奖励模型、使用 PPO 优化策略是三个不同步骤。',limitation:'演示奖励排序损失与相对参考策略的 KL 约束，不实现完整 PPO、价值网络或参数更新。',exercise:'改变人类偏好和策略偏移，观察奖励排序损失，以及提高 KL 系数后的惩罚变化。',dependencies:['08'],quiz:{question:'奖励模型和策略模型输出相同类型的数据吗？',options:['都只输出分数','奖励模型评价回答，策略产生回答分布','奖励模型就是 tokenizer'],answer:1,explanation:'奖励模型提供学习信号，策略模型负责生成。'}},
 {id:'14',name:'Chain-of-Thought',year:2022,group:'工具与推理',title:'Chain-of-Thought Prompting Elicits Reasoning in Large Language Models',file:'14_chain-of-thought.pdf',folder:'ai-papers-02',pages:[1],section:'Abstract · Chain-of-thought exemplars',question:'为什么示例中加入中间步骤会改变任务表达？',principle:'提示示例包含中间推导，模型在同一生成序列中输出推导与答案；并非另加一种神经网络层。',limitation:'使用可验证的算术教学脚本展示中间状态，不调用 LLM，不代表模型内部思维，也不声称长解释保证正确。',exercise:'改动数量和单价，切换直接答案/分步说明，检查每一步是否能由前一步算出。',dependencies:['08'],quiz:{question:'CoT 是 Transformer 中新增的一种层吗？',options:['是','不是，是提示与输出组织方法','是新的卷积核'],answer:1,explanation:'论文研究通过带推导的示例引导生成，而不是更换网络结构。'}},
 {id:'15',name:'Chinchilla',year:2022,group:'规模与计算',title:'Training Compute-Optimal Large Language Models',file:'15_chinchilla.pdf',folder:'ai-papers-02',pages:[1,4],section:'§3 · Compute-optimal allocation',question:'算力固定时，参数更多一定更好吗？',principle:'固定训练计算预算，应在参数量与训练 token 数之间分配；论文给出两者更均衡扩展的经验结果。',limitation:'演示 C≈6ND 的简化预算与自选损失曲面，不使用原论文拟合系数，也不是实际 FLOPs 估价器。',exercise:'保持预算不变拖动参数量，观察训练数据被挤压后总损失上升的位置。',dependencies:['09'],quiz:{question:'预算固定，模型变大时 token 数会怎样？',options:['可无成本增加','在简化 C≈6ND 中必须减少','始终不变'],answer:1,explanation:'参数量和训练 token 数共享同一计算预算。'}},
 {id:'17',name:'LLaMA',year:2023,group:'语言与注意力',title:'LLaMA: Open and Efficient Foundation Language Models',file:'17_llama.pdf',folder:'ai-papers-02',pages:[3],section:'§2.2 Architecture',question:'RMSNorm、RoPE 与 SwiGLU 改变了哪些计算？',principle:'LLaMA 采用前置 RMSNorm、旋转位置编码与 SwiGLU 等结构选择，仍属于自回归 Transformer。',limitation:'拆开演示三个局部算子，不构成完整 LLaMA；RoPE 作用于 Q/K。为隔离旋转，本页各 token 使用同一个可调位置。',exercise:'改变位置看 Q/K 的二维向量对旋转；切换输入偏移，比较 RMSNorm 不减均值的特点。',dependencies:['08'],quiz:{question:'RoPE 通常作用在哪里？',options:['注意力中的 Q/K 向量对','输出文字字符串','仅作用于最终分类标签'],answer:0,explanation:'位置通过旋转进入 Q/K 匹配关系，不是字符旋转。'}},
 {id:'18',name:'GPT-4 报告',year:2023,group:'多模态',title:'GPT-4 Technical Report',file:'18_gpt-4-technical-report.pdf',folder:'ai-papers-03',pages:[1,2],section:'§1–2 · Scope of disclosure',question:'技术报告公开了什么，哪些内容不能推断？',principle:'报告描述图文输入、文本输出与评测，但明确未公开完整架构、模型规模等细节。',limitation:'本课是证据与评测实验，3D 表展示合成评测数据，不画未披露的“真实 GPT-4 内部层”。数据不是报告基准成绩。',exercise:'改变分类阈值，观察准确率与 Brier 分数为何不是同一件事；区分系统可见行为和内部实现证据。',dependencies:['12'],quiz:{question:'能从这份报告确认 GPT-4 的精确层数吗？',options:['能','不能，报告未披露完整架构','只要看输出长度就能算出'],answer:1,explanation:'教学必须尊重论文披露边界，不能把推测画成事实。'}},
 {id:'19',name:'LLaVA',year:2023,group:'多模态',title:'Visual Instruction Tuning',file:'19_llava.pdf',folder:'ai-papers-03',pages:[4,5],section:'Figure 2 · Two-stage instruction tuning',question:'视觉向量如何接入语言模型？',principle:'视觉编码器输出经投影对齐到语言嵌入维度，与指令共同作为语言模型输入；原版采用两阶段训练。',limitation:'本页固定小型视觉向量与线性投影，不加载 CLIP/Vicuna；不混用后续 LLaVA 版本结构。',exercise:'切换对齐预训练/指令微调阶段，查看哪些参数可训练；改变图像特征，看拼接序列和输出分数。',dependencies:['12','08'],quiz:{question:'原版 LLaVA 第二阶段的视觉编码器是否更新？',options:['始终更新','仍冻结，更新投影与语言模型','只更新视觉编码器'],answer:1,explanation:'原论文第 5 页明确说明两阶段的冻结与更新范围。'}},
 {id:'20',name:'Segment Anything',year:2023,group:'多模态',title:'Segment Anything',file:'20_segment-anything.pdf',folder:'ai-papers-03',pages:[4,5],section:'Figure 4 · §3',question:'点击一个点，为什么能改变分割目标？',principle:'图像编码可复用；点、框等提示经编码后与图像嵌入交互，由轻量 mask decoder 产生候选掩码。',limitation:'用灰度相似度与距离函数替代训练网络，仅演示提示依赖；不能称为 SAM 推理，掩码和阈值不代表原模型质量。',exercise:'点击输入图的不同像素作为正提示，再调阈值，看掩码如何变化；比较两个候选掩码的歧义。',dependencies:['10'],quiz:{question:'同一张图连续改变提示，必须重新执行重型图像编码吗？',options:['必须','设计上可以复用图像嵌入','不需要任何图像信息'],answer:1,explanation:'分离图像编码和提示/掩码解码是交互效率的重要来源。'}},
 {id:'21',name:'ReAct',year:2022,group:'工具与推理',title:'ReAct: Synergizing Reasoning and Acting in Language Models',file:'21_react.pdf',folder:'ai-papers-04',pages:[1,3],section:'§2 · Reasoning + Acting',question:'模型动作与外部观察如何构成循环？',principle:'把任务规划、行动与环境反馈交替放入上下文，工具返回的信息会影响下一步动作。',limitation:'本地脚本模拟任务状态与计算器反馈，不调用外部工具或 LLM，也不展示真实模型的私有思维过程。',exercise:'把工具返回切成失败，单步查看流程如何进入重试，而不是直接把假定结果当作观察。',dependencies:['14'],quiz:{question:'Observation 应该来自哪里？',options:['随意补写一个结果','工具或环境的实际返回','上一条提示的标题'],answer:1,explanation:'行动是否成功必须由返回证据判断，不能用计划替代观察。'}},
 {id:'22',name:'Toolformer',year:2023,group:'工具与推理',title:'Toolformer: Language Models Can Teach Themselves to Use Tools',file:'22_toolformer.pdf',folder:'ai-papers-04',pages:[2,3],section:'Figure 2 · Filtering API calls',question:'怎样筛选真正有用的工具调用训练样本？',principle:'采样候选调用、执行工具，再比较加入结果前后的后续 token 预测损失，只保留足够有帮助的调用。',limitation:'概率与候选调用是教学数据；计算保留规则，不执行工具、不做模型微调，也不是在评估真实 API。',exercise:'调节调用带来的概率改善与筛选阈值，看“有调用”为什么不一定“值得保留”。',dependencies:['21'],quiz:{question:'Toolformer 是否把所有生成的调用都用于训练？',options:['是','不是，会按后续预测损失改善筛选','只看 API 名字长度'],answer:1,explanation:'过滤步骤区分有帮助与无帮助的工具返回。'}},
 {id:'23',name:'Mixtral',year:2024,group:'语言与注意力',title:'Mixtral of Experts',file:'23_mixtral-of-experts.pdf',folder:'ai-papers-04',pages:[2,3],section:'Figure 1 · §2.1 Sparse MoE',question:'每个 token 怎样选择不同的专家？',principle:'路由器为 token 打分，从八个 FFN 专家中选择两个，对被选输出加权汇总；不是每个专家都运行。',limitation:'保留八选二但把向量缩到 4 维，使用固定的普通 SiLU FFN 替代原 SwiGLU 专家；不声称复现模型规模、负载均衡或运行加速。',exercise:'改变一个输入特征，观察两名入选专家是否切换，以及路由权重是否仍和为 1。',dependencies:['17'],quiz:{question:'同一层中不同 token 必须选择相同专家吗？',options:['必须','不必，路由按 token 进行','专家由词表 ID 永久决定'],answer:1,explanation:'选择依据当前层的隐藏表示，不是固定语义标签。'}},
 {id:'24',name:'DeepSeek-R1',year:2025,group:'搜索与强化学习',title:'DeepSeek-R1: Incentivizing Reasoning Capability in LLMs via Reinforcement Learning',file:'24_deepseek-r1.pdf',folder:'ai-papers-04',pages:[2,3,6],section:'§2.1 · Equations 1–3 · R1 pipeline',question:'同一个问题的多条回答怎样相互比较？',principle:'GRPO 用组内奖励统计构造相对优势；R1-Zero 与包含冷启动、多阶段训练的 R1 路线不同。',limitation:'只展示奖励、标准化优势与裁剪项，不训练策略，不模拟真正推理能力涌现；零方差组按教学实现置零。',exercise:'把同组奖励设为完全相同，观察优势为何为零；再给一条回答更高奖励，观察正负优势。',dependencies:['13'],quiz:{question:'R1 和 R1-Zero 的训练流程完全一样吗？',options:['一样','不一样，R1 包含冷启动等额外阶段','R1 不使用强化学习'],answer:1,explanation:'论文专门区分两条训练路线，不能混写。'}},
 {id:'25',name:'MMaDA',year:2025,group:'扩散与生成',title:'MMaDA: Multimodal Large Diffusion Language Models',file:'25_mmada.pdf',folder:'ai-papers-04',pages:[2,4,5,6],section:'§2 · Masked-token objectives and UniGRPO',question:'文本与图像 token 能否共享离散去噪视角？',principle:'通过统一离散掩码预测处理多模态序列，再结合混合长推导数据与面向扩散的后训练方法。',limitation:'演示条件片段保持可见、响应片段掩码重建；不运行图像 tokenizer 或完整 UniGRPO，不把它简化成普通自回归连乘。',exercise:'改变响应掩码比例，观察损失只覆盖哪些位置；与 DDPM 的连续高斯噪声比较。',dependencies:['11','24'],quiz:{question:'离散扩散的序列概率可直接照搬自回归链式逐 token 连乘吗？',options:['总可以','不能直接照搬，条件和掩码机制不同','它根本没有 token'],answer:1,explanation:'论文指出掩码依赖与非自回归似然估计是后训练中的关键问题。'}}
]
// Main evidence lessons and optional operator appendices have different learning goals.
const mainIntroductions: Record<string, Pick<Paper,'question'|'principle'|'pages'|'section'>> = {
 '23':{question:'同一个词换个语境，专家选择会怎样变化？',principle:'并排定位两个语境的 token，按层核对 gate 概率、Top-k 与加权负载；结合 Table 2 区分模型质量、活跃参数和实际硬件成本。',pages:[2,3,4],section:'§2.1、§3、Table 2'},
 '25':{question:'文本和图像位置如何在多轮去噪中被恢复、遮蔽和改写？',principle:'固定一个实际生成帧作为参照，追踪位置 ID 和解码图；再独立阅读训练阶段消融，避免用采样过程代替训练收益证据。',pages:[6,7,8,12,15],section:'Algorithm 1、采样对照、Table 5'},
 '13':{question:'偏好的回答，与奖励最高的回答会一致吗？',principle:'先按明确准则做匿名排序，再揭示实际来源与可选奖励；比较复评分歧，并区分读者反馈、奖励模型和策略优化。',pages:[3,6,7],section:'主要结果 / §3.1 · 人类偏好与评估条件'},
 '14':{question:'最终答案正确，公开解答的每一步也正确吗？',principle:'用固定题比较直接回答与公开解答，逐行标首错，并从真实输出独立提取答案；过程核查与最终匹配分开。',pages:[20],section:'附录 B Table 1 · 规模与提示对照'},
 '22':{question:'工具返回究竟改善了哪个后续token？',principle:'执行受限计算器，固定目标ID比较三个上下文NLL，按整段基线画损失贡献并筛选；不把筛选当微调。',pages:[2,3,6],section:'过滤公式 / §4.2 / Table 4'},
 '24':{question:'同题候选的奖励，怎样变成组内相对信号？',principle:'从奖励开关进入真实候选核验，计算均值、总体标准差与优势；保留重复、格式失败和全组同分，不自动奖励长度。',pages:[1,3,4,5,6],section:'§2.2–2.3 / Figure 1 / Table 2 · 路线与评估'},
 '02':{question:'策略喜欢的落点，为什么搜索后可能改选？',principle:'从合法落子进入搜索分支，用真实记录联动棋盘、树、访问预算和价值视角；再比较原文策略的准确率与速度取舍。',pages:[1,2,4],section:'策略训练 / Figure 2、4 · 先验、价值和搜索'},
 '03':{question:'一盘棋怎样变成下一轮学习的样本？',principle:'先取得实际搜索访问数，终局后构造(s,π,z)；真实检查点的同局面输出与固定对手评估另外比较。',pages:[2,3,4,5],section:'Equation 1 / Figure 1 / Table 1 · 自我对弈与检验'},
 '05':{question:'标签很少时，预训练收益能怎样被公平比较？',principle:'先比较原文消融的不同指标，再配对同预算、划分和优化设置的实际训练记录，查看每个观测点与错例。',pages:[3,7,8],section:'§3 / Table 5 · 迁移与消融'},
 '06':{question:'逐段开放右侧线索，候选词会怎样改变？',principle:'固定BERT权重，比较无右文和两组逐段开放的右文，追踪真实WordPiece、MASK候选和输入掩码；不将删除后文当作单向预训练。',pages:[4,8],section:'§3.1 / Table 5 · MLM与双向预训练消融'},
 '07':{question:'同一文章后面接什么，模型才知道要做什么？',principle:'比较续写、摘要与问答后缀，以三种颜色和逐token追加看同一模型如何延伸前缀，再回原文核查事实。',pages:[1,2,3],section:'§2 · 语言建模与任务条件'},
 '08':{question:'只动示例卡、不改权重，输出怎样变化？',principle:'单独改变示例数量、顺序、标签名称或错误标签；用明确标注的GPT-2替代模型比较固定四题，保留格式失败与错误回答。',pages:[3,4,23],section:'Figure 1.1 / Table 3.9 · 上下文学习及任务边界'},
 '10':{question:'图片块的内容与位置，分别怎样影响识别？',principle:'在同一张照片上遮挡、交换并检查像素；配置本地ViT后对比实际分类、patch投影与固定位置编码。',pages:[3,5,7],section:'§3 / §4 · 图像patch、模型与数据规模实验'},
 '19':{question:'回答里的细节，图片真的提供了依据吗？',principle:'对同一问题比较原图、遮挡图与可选无图条件，保留真实回答并记录可见依据；输入干预与训练消融分开解释。',pages:[4,5],section:'Figure 2 / §4 · 视觉指令与两阶段训练'},
 '20':{question:'一个点怎样指定分割目标，什么时候还不够？',principle:'添加正负点或框，观察本地SAM的多候选掩码；把图像编码缓存、提示更新与质量预测分开检查。',pages:[4,5],section:'Figure 4 / §3 · 图像编码、提示与掩码'},
 '09':{question:'小模型的实验，能预测多大范围的结果？',principle:'选择原文近似读图点拟合，再用留出点检验；控制条件、读图精度和外推范围共同决定结论边界。',pages:[4,8],section:'§1.1 / Figure 6 · 参数规模与测试损失'},
 '15':{question:'算力固定时，参数与数据怎么分？',principle:'先体验固定预算的约束，再比较三条配置估计路线与 Chinchilla / Gopher 的原文验证。',pages:[3,8,11],section:'Tables 1 / 2 / 6 · 配置、扩展指数与验证'},
 '17':{question:'满足同一任务时，应该选择多大的模型？',principle:'用原文任务成绩和明确的纯权重预算筛选候选；更大的模型不一定在每个任务更好，存储估算也不能替代部署实测。',pages:[3,4],section:'§2 / Table 3 · 架构与 zero-shot 系统成绩'},
 '18':{question:'一句结论，需要哪一份证据才能成立？',principle:'从成绩、反例和披露范围三个证据抽屉中引用原文，区分支持、反驳与证据不足。',pages:[2,7],section:'§2 / Table 2 · 披露范围与基准成绩'},
}
for (const paper of papers) if (mainIntroductions[paper.id]) Object.assign(paper,mainIntroductions[paper.id])
export const groups=[...new Set(papers.map(p=>p.group))]
