import type { Experiment, Settings } from './types'
import { ce, fmt, grid, softmax, stage, sum } from './math'
import sourceCode from './learning.ts?raw'
export function learning(id:string,s:Settings):Experiment {
 if(id==='02'||id==='03') {
  const count=s.visits??12,c=s.explore??1,mix=s.mix??.5,z=s.outcome??1
  const prior=[.6,.3,.1],values=[.15,.5,.8],rollouts=[.7,.2,-.1],n=[0,0,0],q=[0,0,0],history:number[][]=[]
  for(let step=0;step<count;step++) {
   const u=prior.map((p,i)=>c*p*Math.sqrt(sum(n)+1)/(1+n[i])),scores=q.map((v,i)=>v+u[i])
   const action=scores.indexOf(Math.max(...scores)),value=id==='02'?mix*values[action]+(1-mix)*rollouts[action]:values[action]
   n[action]++;q[action]+=(value-q[action])/n[action]
   history.push([step+1,action,value,...n])
  }
  const pi=n.map(v=>v/count),u=prior.map((p,i)=>c*p*Math.sqrt(sum(n)+1)/(1+n[i])),stats=prior.map((p,i)=>[p,n[i],q[i],u[i],q[i]+u[i]])
  const policyLoss=-sum(pi.map((p,i)=>p*Math.log(prior[i]))),valueLoss=(z-.25)**2
  const stages=[stage('policy','网络输出 p 与 v',[prior,[.25,.25,.25]],'三种候选行动的先验，下面重复的 .25 仅显示同一个根节点标量 v，非每动作价值。未使用训练网络。','(p,v)=fθ(s)','p, v = fixed_policy_and_value',[],{axes:['example','p-or-v','action'],kind:'state',rows:['p','v（重复显示）']}),stage('leaf','候选叶子评价',[values,id==='02'?rollouts:values],id==='02'?'原版 AlphaGo 的价值估计和 rollout 结果是不同来源。本例固定三组数。':'AlphaZero 使用网络评估与搜索；此处不引入 AlphaGo 的 rollout 混合。',id==='02'?'vleaf = λ·vnetwork + (1−λ)·zrollout':'vleaf = vnetwork',id==='02'?'leaf_value = mix * value + (1-mix) * rollout':'leaf_value = value',['policy'],{kind:'state',axes:['example','source','action'],rows:id==='02'?['value','rollout']:['value','value（对照）']}),stage('search','根节点搜索统计',stats,'每行是一个行动；列依次 P、N、Q、探索项 U、Q+U。本例是根节点 bandit 简化，不是完整 MCTS。','Utoy=c·P·√(Ntotal+1)/(1+Na)','a = argmax(Q + U); N[a] += 1; Q[a] += (leaf-Q[a])/N[a]',['policy','leaf'],{kind:'state',axes:['example','action','P/N/Q/U/score'],rows:['行动0','行动1','行动2']}),stage('trajectory','最近八次模拟',history.slice(-8),'每行依次是步数、选中动作、回传值、三个动作访问次数。全部由上面的更新规则算出。','Qnew = Qold + (value−Qold)/N','history.append([step, action, value, *N])',['search'],{kind:'state',axes:['example','simulation','step/action/value/N']}),stage('policy-target','搜索改进后的 π',[pi],'把访问次数归一化得到搜索分布；未执行网络更新。','πa=Na / Σb Nb','pi = visits / visits.sum()',['search'],{kind:'state',axes:['example','root','action'],probability:true})]
  if(id==='03')stages.push(stage('loss','策略与价值训练目标',[[policyLoss,valueLoss]],'计算论文目标中的两项，省略参数正则项。这里只算损失，不反向传播。','L=−πᵀlog p+(z−v)²+c||θ||²','loss = -(pi*p.log()).sum() + (z-v)**2',['policy-target','policy'],{kind:'measurement',axes:['example','root','policy/value']}))
  return {knobs:[{key:'visits',title:'模拟次数',min:1,max:80,step:1,initial:12},{key:'explore',title:'探索强度 c',min:0,max:3,step:.1,initial:1},...(id==='02'?[{key:'mix',title:'网络价值权重 λ',min:0,max:1,step:.1,initial:.5}]:[{key:'outcome',title:'终局结果 z',min:-1,max:1,step:1,initial:1,labels:{[-1]:'输',0:'平',1:'赢'}}])],stages,metrics:[{label:'访问次数',value:n.join(' / ')},{label:'最多访问的行动',value:String(n.indexOf(Math.max(...n)))}],observations:['提高探索系数可能增加对低访问动作的尝试。','图中固定叶子值不是训练网络或实际对局结果。'],sourceCode}
 }
 if(id==='13') {
  const preferred=s.preferred??0,shift=s.shift??0,beta=s.beta??.5,rewards=[.7,-.2],chosen=rewards[preferred],rejected=rewards[1-preferred]
  const ranking=Math.log1p(Math.exp(-(chosen-rejected))),p=softmax([shift,-shift]),ref=[.5,.5]
  const klTerms=p.map((v,i)=>v*Math.log(v/ref[i])),kl=sum(klTerms),expected=sum(p.map((v,i)=>v*rewards[i]))
  return {knobs:[{key:'preferred',title:'标注者更喜欢哪条回答',min:0,max:1,step:1,initial:0,labels:{0:'回答 A',1:'回答 B'}},{key:'shift',title:'策略 logit 偏移',min:-2,max:2,step:.2,initial:0},{key:'beta',title:'KL 系数 β',min:0,max:2,step:.1,initial:.5}],stages:[stage('sft','SFT 示范位置',[[1,0],[0,1]],'用两条抽象的示范标签表示监督目标；此表是教学数据，不是模型隐藏状态。','LSFT=−Σ log πθ(y*|x)','sft_loss = cross_entropy(policy_logits, demonstration)',[],{kind:'state',axes:['example','prompt','target']}),stage('preference','人类偏好与奖励分数',rewards.map((v,i)=>[i===preferred?1:0,v]),'第一列是人类选择，第二列是固定奖励模型分数。改变偏好会改变排序损失，但不会自动更新奖励模型。','LRM=−log σ(rchosen−rrejected)','rm_loss = -logsigmoid(r_chosen-r_rejected)',['sft'],{kind:'state',axes:['example','answer','chosen/reward'],rows:['A','B']}),stage('policy','策略与参考分布',[p,ref],'策略控制生成回答的概率；参考策略用于限制偏移。','π=softmax([δ,−δ])','policy = softmax(logits); reference = [.5,.5]',['preference'],{probability:true,axes:['example','policy','answer'],rows:['当前','参考']}),stage('objective','奖励与 KL',[[expected,kl,beta*kl,expected-beta*kl]],'列为期望奖励、KL、加权惩罚、差值。是 RLHF 目标的局部教学，不是完整 PPO 更新。','Jtoy=Eπ[r]−β KL(π||πref)','objective = (policy*reward).sum() - beta*KL(policy,reference)',['policy','preference'],{kind:'measurement',axes:['example','row','reward/KL/penalty/objective']})],metrics:[{label:'奖励排序损失',value:fmt(ranking)},{label:'KL',value:fmt(kl)},{label:'教学目标',value:fmt(expected-beta*kl)}],observations:['偏好是训练信号，不是输入图片类别。','为了奖励过度改变策略可能带来更高的 KL 惩罚。'],sourceCode}
 }
 const equal=s.equal??0,chosen=s.reward??1,rewards=equal?[chosen,chosen,chosen,chosen]:[chosen,0,1,-.5]
 const mean=sum(rewards)/4,std=Math.sqrt(sum(rewards.map(v=>(v-mean)**2))/4),adv=rewards.map(v=>std<1e-8?0:(v-mean)/std),shift=s.shift??0
 const p=softmax([shift,0,0,0]),ratios=p.map(v=>v/.25),terms=ratios.map((r,i)=>Math.min(r*adv[i],Math.max(.8,Math.min(1.2,r))*adv[i]))
 return {knobs:[{key:'reward',title:'第一条回答的奖励',min:-1,max:2,step:.25,initial:1},{key:'equal',title:'组内奖励',min:0,max:1,step:1,initial:0,labels:{0:'各不相同',1:'全部相同'}},{key:'shift',title:'第一候选新策略偏移',min:-2,max:2,step:.2,initial:0}],stages:[stage('rewards','同题四条回答的奖励',rewards.map(v=>[v]),'同一个问题采样一组回答。这里奖励由用户设定，不是调用评测器。','r=[r₁,r₂,r₃,r₄]','rewards = score(completions)',[],{kind:'state',axes:['group','answer','reward']}),stage('statistics','组内均值与标准差',[[mean,std]],'采用总体标准差作教学约定。相同奖励时标准差为零，程序定义优势为零避免除零。','μ=mean(r), σ=std(r)','mu = rewards.mean(); sigma = rewards.std(unbiased=False)',['rewards'],{kind:'measurement',axes:['group','row','mean/std']}),stage('advantage','相对优势',adv.map(v=>[v]),'高于本组均值为正，低于均值为负；不是绝对奖励分数。','Aᵢ=(rᵢ−μ)/σ','advantages = (rewards-mu)/sigma if sigma>0 else zeros_like(rewards)',['rewards','statistics'],{kind:'measurement',axes:['group','answer','advantage']}),stage('ratio','新旧策略与比例',p.map((v,i)=>[.25,v,ratios[i]]),'将四个完整回答视为四类行动，省略真实序列内 token 细节。','ρᵢ=πnew(oi)/πold(oi)','ratio = new_prob / old_prob',['advantage'],{kind:'measurement',axes:['group','answer','old/new/ratio']}),stage('clip','裁剪 surrogate',terms.map(v=>[v]),'计算 min(ρA,clip(ρ)A)。这里只展示局部项，完整 GRPO 还涉及序列与 KL，不执行训练。','min(ρᵢAᵢ,clip(ρᵢ,0.8,1.2)Aᵢ)','surrogate = minimum(ratio*A, ratio.clamp(.8,1.2)*A)',['ratio','advantage'],{kind:'measurement',axes:['group','answer','surrogate']})],metrics:[{label:'组均值',value:fmt(mean)},{label:'组标准差',value:fmt(std)},{label:'平均裁剪项',value:fmt(sum(terms)/4)}],observations:['全组奖励相等时，没有组内相对优劣信号。','R1-Zero 的 RL-only 与 R1 冷启动等多阶段训练不同。'],sourceCode}
}
