export interface MathLesson {
 id:string;title:string;english:string;question:string;papers:string[];source:string;page:number;pages?:number[]
 prerequisites:string;symbols:[string,string][];steps:{title:string;formula:string;explanation:string}[];boundary:string
}
export const mathLessons:MathLesson[]=[
{id:'residual',title:'残差相加与梯度路径',english:'Residual connection',question:'加回输入为什么不会增加通道数？',papers:['01'],source:'ResNet §3.1–3.2 · 残差映射与投影捷径',page:3,prerequisites:'逐元素加法；导数的加法法则。',symbols:[['x','块输入，形状为[B,C,H,W]'],['F(x)','主分支计算的改变量'],['Wₛ','当维度不匹配时的捷径投影'],['I','恒等映射的雅可比矩阵']],steps:[{title:'把目标改写为“原值 + 改变量”',formula:'H(x) = x + F(x)    ⇔    F(x) = H(x) − x',explanation:'先定义我们要得到的目标H，再让主分支拟合与输入之间的差。两边形状相同才能逐元素相加；加法不同于拼接。'},{title:'形状不同时，先对齐',formula:'s = Wₛx + F(x) ;    y = ReLU(s)',explanation:'恒等捷径是Wₛ=I的情况。原文基本块相加后还有ReLU，所以F=0时，包含ReLU的整个块不一定对负输入保持恒等。'},{title:'局部梯度从两条路径到达输入',formula:'∂y/∂x = diag(1[s > 0]) · (I + J_F(x))',explanation:'这里限恒等捷径，且避开ReLU在0处的不可导点。J_F是主分支雅可比。I提供额外路径，但ReLU门控、后续层和优化条件仍会影响梯度，不能直接证明永不消失。'}],boundary:'下方是单个标量的加法例子，不是训练结果或完整卷积网络。'},
{id:'attention',title:'从点积到注意力加权和',english:'Scaled dot-product attention',question:'两个向量的匹配，怎样变成读取内容的权重？',papers:['04','06','07','08','10','19'],source:'Attention Is All You Need §3.2.1 · Scaled Dot-Product Attention',page:4,prerequisites:'向量点积、指数、按行归一化。',symbols:[['Q ∈ ℝⁿˣᵈ','n个查询，每个宽度d'],['K ∈ ℝᵐˣᵈ','m个键，匹配维度同为d'],['V ∈ ℝᵐˣᵈᵥ','与每个键对应的内容'],['A ∈ ℝⁿˣᵐ','每个查询对各键的权重']],steps:[{title:'先计算位置之间的匹配',formula:'S = QKᵀ / √d ;    Sᵢⱼ = Σₖ Qᵢₖ Kⱼₖ / √d',explanation:'n个Query逐一与m个Key做点积，因此关系表是n×m。不是隐藏维度×隐藏维度。除以√d用于控制分数尺度；独立、零均值、单位方差分量下，未缩放点积方差随d增长。'},{title:'屏蔽不可读的位置，再按行归一化',formula:'Aᵢⱼ = exp(Sᵢⱼ + Mᵢⱼ) / Σₗ exp(Sᵢₗ + Mᵢₗ)',explanation:'允许读的位置M=0，禁止读的位置M=−∞；每行至少要有一个可读位置。softmax沿键位置归一化，每行和为1。为数值稳定可先减去该行最大值，结果不变。'},{title:'用权重汇总内容',formula:'O = AV ;    Oᵢ = Σⱼ Aᵢⱼ Vⱼ',explanation:'分数来自Q/K，真正被汇总的内容来自V。输出为n×dᵥ。多头分别计算后拼接并投影；本站数值例子只展开一个Query和两个Key。'}],boundary:'下方用两个标量score和标量Value解释softmax与汇总；温度τ是教学控制，τ=1对应这里的标准公式。'},
{id:'likelihood',title:'概率、交叉熵与负对数似然',english:'Cross-entropy / negative log-likelihood',question:'为什么提高正确token的概率会降低损失？',papers:['05','06','07','22','25'],source:'GPT-1 §3 · 语言模型与监督目标；Toolformer的后续token损失过滤另见该课',page:3,prerequisites:'概率介于0与1之间；自然对数ln。',symbols:[['pθ(y|c)','给定上下文c，对目标y的预测概率'],['y','真实标签或目标token'],['L','负对数似然损失'],['wₜ','指定位置的非负权重']],steps:[{title:'把乘积变成可加的量',formula:'P(y₁:T) = ∏ₜ pθ(yₜ | y<ₜ)\n−ln P(y₁:T) = −Σₜ ln pθ(yₜ | y<ₜ)',explanation:'这里是自回归分解。取对数把乘积变成求和，负号使提高目标概率对应减小损失。这不是直接适用于所有扩散模型的似然计算公式。'},{title:'单标签交叉熵与NLL相同',formula:'CE(q,p) = −Σᵢ qᵢ ln pᵢ ;    q_y=1 ⇒ CE=−ln p_y',explanation:'当目标是one-hot分布，只有正确类别那一项留下。软标签时要保留所有非零项。p=0时损失趋向正无穷，所以算例不允许概率取0。'},{title:'比较同一组后续token',formula:'L = −Σₜ wₜ ln pθ(yₜ | cₜ)\nΔ = min(L_no-call, L_empty) − L_result',explanation:'第二行是Toolformer过滤思路的教学写法。比较时目标位置、token与权重必须对齐；空返回基线帮助分离调用文本本身的作用。达到阈值只说明候选被保留，之后仍需训练。'}],boundary:'算例只计算一个目标概率的NLL。既不运行语言模型，也不等于完整Toolformer过滤实现。'},
{id:'diffusion',title:'多步加噪为什么能写成一个公式',english:'Forward diffusion',question:'怎样直接从原图得到任意时刻的噪声图？',papers:['11'],source:'DDPM §2 · 前向过程与累积噪声',page:2,prerequisites:'高斯分布；独立随机变量相加时方差相加。',symbols:[['βₜ','第t步加入的噪声方差'],['αₜ=1−βₜ','该步保留系数'],['ᾱₜ=∏ₛ₌₁ᵗ αₛ','从起点累计的保留系数'],['ε ∼ N(0,I)','标准高斯噪声']],steps:[{title:'一步加入噪声',formula:'xₜ = √αₜ xₜ₋₁ + √(1−αₜ) εₜ',explanation:'系数用平方根，是因为随机噪声的方差由系数平方决定。xₜ与xₜ₋₁形状相同。'},{title:'展开两步并合并独立高斯项',formula:'x₂ = √(α₂α₁)x₀ + √(α₂(1−α₁))ε₁ + √(1−α₂)ε₂\nVar(noise) = α₂(1−α₁) + (1−α₂) = 1−α₂α₁',explanation:'这里ε₁与ε₂独立。均值为0，方差相加，因此两项的和可以表示为另一标准高斯乘以总标准差。'},{title:'推广到任意时刻',formula:'xₜ = √ᾱₜ x₀ + √(1−ᾱₜ) ε',explanation:'不必逐步运行前向过程就能采样xₜ。下方固定一个ε只为了公平观察系数变化，不是一条严格逐步马尔可夫采样轨迹。反向生成还需要训练出的噪声预测器。'}],boundary:'算例是单像素、固定噪声的前向数学，没有去噪模型或照片修复。'},
{id:'contrast',title:'图文相似度与对比目标',english:'Contrastive learning',question:'为什么CLIP分数会随候选文字变化？',papers:['12'],source:'CLIP §2.3 · 对称图文对比目标',page:5,prerequisites:'向量长度、点积、softmax和交叉熵。',symbols:[['uᵢ,vⱼ','单位长度的图像/文字表示'],['s','正的logit缩放系数'],['Zᵢⱼ=s·uᵢᵀvⱼ','第i图与第j文本的匹配分数'],['N','配对图文批次大小']],steps:[{title:'先消除向量长度的影响',formula:'u = f(image)/‖f(image)‖₂ ;    v = g(text)/‖g(text)‖₂',explanation:'长度非零时，单位向量点积就是余弦相似度。归一化不会让模型自动学会匹配，表示本身仍需要训练。'},{title:'在一组候选内归一化',formula:'p(j|image_i) = exp(Zᵢⱼ) / Σₖ exp(Zᵢₖ)',explanation:'改变候选会改变分母，即使原图与某个文本的点积不变，它的概率也可能变化。这是候选内的相对分数。'},{title:'训练同时检查两个方向',formula:'L = ½ [CE(Z, paired_indices) + CE(Zᵀ, paired_indices)]',explanation:'每张图应匹配自己的文字，每段文字也应匹配自己的图片；CE在每个方向对批次取平均。本站单图候选排名不计算这个完整批内训练损失。'}],boundary:'下方两候选算例只演示softmax，不加载CLIP，也不估计分类正确率。'},
{id:'moe',title:'Top-k路由与加权合并',english:'Sparse mixture of experts',question:'只运行两个专家，怎样合成一个输出？',papers:['23'],source:'Mixtral §2.1 · Sparse Mixture of Experts',page:2,prerequisites:'softmax、排序、加权和。',symbols:[['z','路由器为各专家给出的分数'],['S','Top-k选中专家集合'],['wᵢ','只在选中集合内归一化的权重'],['Eᵢ(x)','第i位专家对输入的输出']],steps:[{title:'先决定运行谁',formula:'S = TopK(z) ;    pᵢ = softmax(z)ᵢ',explanation:'softmax严格保持分数排序，因此可以按z或p选集合；平分时具体实现可能选不同专家。这里只运行集合内的专家，但其他权重仍需存储。'},{title:'重新分配选中的概率',formula:'wᵢ = pᵢ / Σⱼ∈S pⱼ = exp(zᵢ)/Σⱼ∈S exp(zⱼ), i∈S',explanation:'未选专家权重为0，选中的权重和为1。对全部专家softmax再选中归一化，等价于只对选中logit做softmax。'},{title:'相加，不是拼接',formula:'y = Σᵢ∈S wᵢ Eᵢ(x)',explanation:'如果每位专家输出宽度D，那么加权和仍为D。专家选择依赖当前层的隐藏状态，不能由一次选择推断固定语义分工。'}],boundary:'算例缩为3选2并使用手动指定的标量专家输出；不是Mixtral真实路由。'},
{id:'advantage',title:'组内奖励怎样变成相对优势',english:'Group-relative advantage',question:'为什么同一奖励在不同组里意义不同？',papers:['24','13'],source:'DeepSeek-R1 · GRPO组内相对信号；本算例仅展示标准化部分',page:3,prerequisites:'均值、方差、标准差。',symbols:[['G','同一问题的候选数量'],['rᵢ','候选i的奖励'],['μ,σ','本组均值和标准差'],['Âᵢ','候选i的标准化优势']],steps:[{title:'找到本组参照',formula:'μ = (1/G) Σᵢ rᵢ',explanation:'均值是当前组的参照，不是一个全局正确性标准。同一回答与不同候选组比较，得到的相对信号可能不同。'},{title:'衡量组内差异',formula:'σ = √[(1/G) Σᵢ (rᵢ−μ)²]',explanation:'本站为明确教学，使用总体标准差，即除以G。实际训练实现还需核对标准差估计、数值稳定项和奖励归一化配置。'},{title:'构造相对信号',formula:'Âᵢ = (rᵢ−μ)/σ    (σ>0)',explanation:'高于平均为正，低于平均为负。当所有奖励相同，本算例把优势置0。完整GRPO还包含策略比率、裁剪和KL等项，不能把这一行当作全部目标函数。'}],boundary:'只做四个奖励的算术，没有策略训练；零方差置零为教学约定。'},
{id:'budget',title:'参数、数据与计算预算',english:'Compute-optimal allocation',question:'计算量固定，参数翻倍意味着什么？',papers:['15','09','17'],source:'Chinchilla §3.3 · 损失模型（PDF第6页）；计算预算约束与闭式解（第7页）',page:6,pages:[6,7],prerequisites:'乘法约束、数量级、对数。',symbols:[['C','训练计算量，单位FLOPs'],['N','模型参数个数'],['D','训练token数量'],['a,b,α,β','通过实验估计的正参数']],steps:[{title:'先给定近似成本约束',formula:'C ≈ 6ND    ⇒    D ≈ C/(6N)',explanation:'固定C时，N增大意味着D减小。这是粗略训练计算估算，不覆盖所有系统开销，也不能直接换算GPU时长。'},{title:'用实验拟合质量模型',formula:'L(N,D) ≈ L∞ + aN^(−α) + bD^(−β)',explanation:'模型受参数与数据两方面限制。各项参数需要受控实验估计，不应为了画漂亮曲线任意设定后当作原文成绩。'},{title:'约束下寻找驻点',formula:'D=C/(6N)\nαaN^(−α−1) = βb(6/C)^β N^(β−1)',explanation:'把D代回损失，对N求导并设为0，可得N^(α+β)=[αa/(βb)](C/6)^β。这个模型下N∝C^[β/(α+β)]，D∝C^[α/(α+β)]；不必预设永远各占一半指数。'}],boundary:'算例只展示成本约束，不拟合论文参数、不预测质量或采购成本。'},
{id:'selfplay',title:'搜索策略和终局价值的联合损失',english:'Policy-value learning',question:'同一盘棋为什么能监督两个输出？',papers:['03','02'],source:'AlphaZero · Equation 1，自我对弈训练目标',page:3,prerequisites:'平方误差、交叉熵与向量范数。',symbols:[['p,v','网络输出的策略分布与价值'],['π,z','搜索分布与终局结果目标'],['θ','网络参数'],['c','权重正则系数']],steps:[{title:'把访问数转成策略目标',formula:'πₐ = Nₐ^(1/τ) / Σ_b N_b^(1/τ)    (τ>0)',explanation:'这里用温度参数给出访问数归一化的一般教学形式；原文此页说明按访问数比例或贪心选择。访问多的行动通常获得更高目标概率，τ控制尖锐程度。τ趋近0时趋向选择最大访问行动。这里是搜索目标，不是网络原始p。'},{title:'两个输出对应两个目标',formula:'L = (z−v)² − Σₐ πₐ ln pₐ + c‖θ‖₂²',explanation:'第一项让价值接近从当前行动者视角看的终局结果；第二项让网络策略接近搜索分布；第三项为权重正则。'},{title:'每个状态都要统一视角',formula:'z_current = +1（当前行动者最终获胜）\nz_current = −1（当前行动者最终失败）\nz_current = 0（平局）',explanation:'切换行动者会改变胜负标签的解释。得到这个损失数值后，还需要梯度更新才能叫训练；页面规则搜索不会自动产生学到的网络。'}],boundary:'数值练习只计算一项价值平方误差，未运行搜索或反向传播。'}
]
export function relatedMath(paperId:string){return mathLessons.filter(m=>m.papers.includes(paperId))}
