import type { Experiment, Settings } from './types'
import { add, attention, ce, dot, embedding, fmt, grid, image, mm, silu, softmax, stage, sum, transpose, weights } from './math'
import sourceCode from './multimodal.ts?raw'
export function multimodal(id:string,s:Settings):Experiment {
 if(id==='12') {
  const tau=s.temperature??.2,swap=s.swap??0,visual=[[1,.2,0,.1],[.1,1,.2,0],[0,.2,1,.3]],text=[[1,.1,0,.1],[0,1,.1,.2],[.1,.1,1,.2]]
  if(swap)[text[0],text[1]]=[text[1],text[0]]
  const unit=(x:number[][])=>x.map(row=>{const l=Math.sqrt(dot(row,row));return row.map(v=>v/l)}),vi=unit(visual),tx=unit(text),similarity=mm(vi,transpose(tx)),logits=similarity.map(row=>row.map(v=>v/tau)),i2t=logits.map(softmax),t2i=transpose(logits).map(softmax)
  const loss=(sum(i2t.map((row,i)=>ce(row,i)))+sum(t2i.map((row,i)=>ce(row,i))))/6
  return {knobs:[{key:'temperature',title:'温度 τ',min:.05,max:1,step:.05,initial:.2},{key:'swap',title:'文本配对',min:0,max:1,step:1,initial:0,labels:{0:'原始顺序',1:'交换前两段文本'}}],stages:[stage('raw','两路特征',[visual,text],'三对手工特征代替真实图像/文本编码器；共同维度为 4。','I,T ∈ R^(3×4)','image_features = image_encoder(images)\ntext_features = text_encoder(texts)',[],{planes:['图像','文本'],axes:['B','modality','pair','D']}),stage('unit','L2 归一化',[vi,tx],'把每行变成单位向量，点积就变为余弦相似度。','u=x/||x||₂','i = normalize(image_features); t = normalize(text_features)',['raw'],{planes:['图像单位向量','文本单位向量'],axes:['B','modality','pair','D']}),stage('scores','图文相似度',similarity,'每张图与全部文本比较；对角线是固定训练配对标签。交换文本而不改标签会制造错配。','S=I Tᵀ','scores = i @ t.T',['unit'],{axes:['B','image','text']}),stage('probabilities','双向配对概率',[i2t,t2i],'第一张表行归一化为图找文；第二张表是转置后行归一化，为文找图。','Pimage=softmax(S/τ); Ptext=softmax(Sᵀ/τ)','loss = (CE(scores/tau,diag)+CE(scores.T/tau,diag))/2',['scores'],{probability:true,planes:['image → text','text → image'],axes:['B','direction','query','candidate']})],metrics:[{label:'对称交叉熵',value:fmt(loss)},{label:'第一张图最相似文本索引',value:String(i2t[0].indexOf(Math.max(...i2t[0])))}],observations:['降低温度会使同一相似度的概率分布更尖锐。','错配的标签会提高对比损失，不会自动修复数据。'],sourceCode}
 }
 if(id==='18') {
  const threshold=s.threshold??.5,over=s.confidence??1,labels=[1,1,0,1,0,0],base=[.8,.6,.7,.3,.2,.1],pred=base.map(p=>1/(1+Math.exp(-Math.log(p/(1-p))*over))),decision=pred.map(p=>p>=threshold?1:0)
  const confusion=grid(2,2,()=>0);labels.forEach((y,i)=>confusion[y][decision[i]]++)
  const brier=sum(pred.map((p,i)=>(p-labels[i])**2))/6,correct=sum(decision.map((v,i)=>v===labels[i]?1:0))/6
  return {knobs:[{key:'threshold',title:'正类决策阈值',min:.1,max:.9,step:.1,initial:.5},{key:'confidence',title:'合成分数尖锐程度',min:.5,max:3,step:.25,initial:1}],stages:[stage('evidence','公开事实与未知',[[1,0],[1,0],[0,1]],'两列分别代表“报告披露”与“未披露”；三行是图文输入、文本输出、精确内部架构。不是模型激活。','known ≠ inferred','facts = {image_text_input: true, text_output: true, exact_architecture: unknown}',[],{rows:['图文输入','文本输出','精确架构'],kind:'state',axes:['record','claim','known/unknown']}),stage('records','合成评测记录',labels.map((y,i)=>[y,pred[i],decision[i]]),'六条人造二分类记录，列为真值、正类分数、阈值决策。不是 GPT-4 的测试结果。','ŷ=I[p≥threshold]','prediction = probability >= threshold',[],{kind:'measurement',axes:['dataset','case','truth/prediction/decision']}),stage('confusion','混淆矩阵',confusion,'行是真值，列是决策，两个维度都是类别，不是 token。','C[y,ŷ] += 1','confusion[truth, prediction] += 1',['records'],{kind:'measurement',axes:['dataset','truth','prediction']}),stage('metrics','评测指标',[[correct,brier]],'准确率依赖阈值，Brier 衡量概率与真值的平方差。单一指标无法完整描述能力。','Accuracy=mean(ŷ=y); Brier=mean((p−y)²)','accuracy = mean(pred == y); brier = mean((p-y)**2)',['records','confusion'],{kind:'measurement',axes:['dataset','summary','accuracy/Brier']})],metrics:[{label:'合成准确率',value:fmt(correct)},{label:'合成 Brier',value:fmt(brier)}],observations:['这里的 3D 表是证据与评测数据，不是未披露的内部层。','报告可讨论公开行为与评测，不能凭空补出参数量与层数。'],sourceCode}
 }
 if(id==='19') {
  const phase=s.phase??0,variation=s.visual??0,features=embedding([1+variation,2,3,4],3),projected=mm(features,weights(3,4,4)),text=embedding([5,6,7]),sequence=[...projected,...text],att=attention(sequence,true),out=mm(att.out.slice(-1),weights(4,6,3)).map(softmax)
  return {knobs:[{key:'phase',title:'原版 LLaVA 训练阶段',min:0,max:1,step:1,initial:0,labels:{0:'特征对齐',1:'指令微调'}},{key:'visual',title:'改变第一块视觉特征',min:0,max:2,step:1,initial:0}],stages:[stage('vision','视觉编码结果',features,'四个视觉位置各有三维特征，代替 CLIP 编码器输出。实际编码器始终冻结。','Zv ∈ R^(1×4×3)','zv = frozen_vision_encoder(image)',[],{axes:['B','patch','Dvision']}),stage('projection','对齐语言维度',projected,'投影把 3 维视觉特征变成 4 维语言模型输入；不需要先翻译成文字。','Hv=Zv W；W∈R^(3×4)','hv = zv @ projection',['vision']),stage('text','文本嵌入',text,'语言指令本身也先经过 Embedding。','Ht ∈ R^(1×3×4)','ht = token_embedding(instruction_ids)'),stage('sequence','合并输入序列',sequence,'沿序列维拼接，特征维必须一致；长度变为 4+3=7。','H=[Hv;Ht] ∈ R^(1×7×4)','h = concatenate([hv, ht], axis=1)',['projection','text']),stage('attention','语言模型的因果关系',att.a,'后面的文本位置可以读取前面的图像特征。本例一个小型注意力子层。','A=softmax(QKᵀ/√D+Mcausal)','a = causal_attention(h)',['sequence'],{probability:true,axes:['B','query','key']}),stage('answer','末尾候选词分布',out,'演示从视觉与文本共同输入到文本输出的路径；无真实问答能力。','pnext=softmax(Hlast Wvocab)','p = vocab_head(hidden[:,-1]).softmax(-1)',['attention'],{probability:true,axes:['B','position','vocab']}),stage('trainable','哪些参数可更新',[[0],[1],[phase]],'0=冻结，1=可更新。切换阶段只解释训练计划，不执行参数更新。','Stage1: θ=W；Stage2: θ={W,LLM}','requires_grad = [False, True, phase == 1]',[],{kind:'state',rows:['视觉编码器','投影层','语言模型'],axes:['plan','module','trainable']})],metrics:[{label:'视觉维 → 语言维',value:'3 → 4'},{label:'输入序列长度',value:'7'}],observations:['原版第一阶段只训练投影，第二阶段还更新语言模型。','后续版本可能用不同连接器，本课对应所读的原论文。'],sourceCode}
 }
 if(id==='20') {
  const input=image(),point=s.pixel??14,r=Math.floor(point/6),c=point%6,threshold=s.threshold??.55
  const prompt=grid(6,6,(i,j)=>i===r&&j===c?1:0),scores=grid(6,6,(i,j)=>Math.exp(-Math.abs(input[i][j]-input[r][c])*3)*Math.exp(-((i-r)**2+(j-c)**2)/50))
  const masks=[threshold,Math.min(.95,threshold+.15)].map(t=>scores.map(row=>row.map(v=>v>=t?1:0)))
  return {knobs:[{key:'threshold',title:'教学 mask 阈值',min:.2,max:.8,step:.05,initial:.55}],image:input,imageHint:'点击像素作为正提示，不会改变图像内容',stages:[stage('image','固定图像',input,'同一张图像的信息可供多个提示复用。这里只显示灰度平面，不运行 SAM 图像编码器。','Eimage=ImageEncoder(image)','image_embedding = cached_image_encoder(image)',[],{shape:[1,1,6,6],axes:['B','C','H','W']}),stage('prompt','点提示',prompt,'值为 1 的位置是用户指定的前景点；点击另一个像素改变提示。','prompt=(x,y,label=foreground)','prompt_embedding = encode_point(x,y,label=1)',[],{shape:[1,1,6,6],axes:['B','channel','H','W']}),stage('scores','教学兼容分数',scores,'用灰度相似度×空间距离函数替代训练后的 decoder，只演示输入依赖，不是 SAM 算法。','Sij=exp(−3|Iij−Ip|) exp(−dist²/50)','score = intensity_similarity * spatial_similarity',['image','prompt'],{probability:false,axes:['B','H','W']}),stage('masks','两个候选 mask',masks,'通过两个阈值得到不同范围，说明单点提示可能有歧义。这里没有学习到的 IoU 预测器。','Mij=I[Sij≥τ]','masks = [score>=tau, score>=tau+.15]',['scores'],{planes:['候选 1','候选 2'],axes:['B','candidate','H','W']})],metrics:[{label:'提示坐标 (x,y)',value:`(${c},${r})`},{label:'候选前景像素数',value:masks.map(m=>sum(m.flat())).join(' / ')}],observations:['可见的响应机制是教学替代，不是 SAM 推理结果。','同一正提示可以对应多个合理尺度的区域。'],sourceCode}
 }
 // Mixtral：保持 8 专家、Top-2 机制，缩小特征维度；实际只计算被选专家。
 const x=embedding([1,2,3]).map((row,i)=>row.map((v,j)=>i===0&&j===0?v+(s.feature??0):v)),router=mm(x,weights(4,8,1))
 const chosen=router.map(row=>row.map((v,i)=>({v,i})).sort((a,b)=>b.v-a.v).slice(0,2).map(o=>o.i)),gates=router.map((row,r)=>{const g=softmax(chosen[r].map(i=>row[i]));return row.map((_,i)=>chosen[r].includes(i)?g[chosen[r].indexOf(i)]:0)})
 const branches=[0,1].map(slot=>x.map((row,r)=>{const e=chosen[r][slot];return mm(mm([row],weights(4,8,e+5)).map(v=>v.map(silu)),weights(8,4,e+15))[0]}))
 const output=x.map((_,r)=>branches[0][r].map((v,c)=>v*gates[r][chosen[r][0]]+branches[1][r][c]*gates[r][chosen[r][1]]))
 return {knobs:[{key:'feature',title:'token 0 第一个特征的偏移',min:-4,max:4,step:.25,initial:0}],stages:[stage('input','三个 token',x,'每个 token 四维，不同 token 可选不同专家。','X ∈ R^(1×3×4)','x = hidden_states'),stage('router','八专家路由分数',router,'对每个 token 产生八个分数，专家编号不等于预设的语义类别。','R=XWg','router_logits = x @ Wg',['input'],{axes:['B','token','expert']}),stage('gate','Top-2 门控',gates,'先保留两个最大 logit，再 Softmax；六个未选专家权重严格为零。','G=softmax(TopK(R,2))','gate = softmax(mask_except_top2(router_logits))',['router'],{probability:true,axes:['B','token','expert']}),stage('chosen','入选专家编号',chosen,'每行是该 token 的两个专家索引。0 是合法专家编号，不是未选标记。','indices=TopK(R,2).indices','selected_experts = router_logits.topk(2).indices',['router'],{kind:'state',axes:['B','token','slot']}),stage('experts','两路专家输出',branches,'平面代表路由槽位而不是固定专家；每行调用 chosen 中对应的 FFN。本例用普通 SiLU FFN 缩小计算，原 Mixtral 专家为 SwiGLU。','Ej(x)=Wdown,j·SiLU(Wup,j x)','outputs = [expert[idx](x) for idx in chosen]',['input','chosen'],{planes:['Top-1 槽位','Top-2 槽位'],axes:['B','slot','token','D']}),stage('merge','按门控权重相加',output,'两路输出相加恢复原始形状，不把两个专家的维度拼在一起。','Yt=Σj∈Top2 Gtj Ej(Xt)','y = sum(gate[j] * expert_output[j] for j in selected)',['experts','gate'])],metrics:[{label:'token 0 入选专家',value:chosen[0].join('、')},{label:'token 0 门控和',value:fmt(sum(gates[0]))},{label:'每个 token 活跃专家数',value:'2 / 8'}],observations:['只计算被路由选中的两个小型 FFN。','全部参数量、活跃参数量和实际延迟是不同指标。'],sourceCode}
}
