import type { Experiment, Settings } from './types'
import { fmt, stage, sum } from './math'
import sourceCode from './tools.ts?raw'
export function toolsLesson(id:string,s:Settings):Experiment {
 if(id==='14') {
  const count=s.count??3,price=s.price??4,show=s.steps??1,total=count*price,discount=2,answer=total-discount
  const values=show?[[count,price,total],[total,discount,answer]]:[[count,price,answer]]
  return {knobs:[{key:'count',title:'物品数量',min:1,max:8,step:1,initial:3},{key:'price',title:'单价',min:2,max:9,step:1,initial:4},{key:'steps',title:'表达方式',min:0,max:1,step:1,initial:1,labels:{0:'直接答案',1:'展示中间步骤'}}],stages:[stage('problem','问题事实',[[count,price,discount]],'买若干物品，单价如左，优惠 2。所有数字由用户控制，不是模型生成。','总价=数量×单价−优惠','facts = [count, unit_price, discount]',[],{kind:'state',axes:['example','problem','count/price/discount']}),stage('work','可验证的中间状态',values,show?'第一行：数量、单价、乘积。第二行：乘积、优惠、最终值。':'这里只展示输入和最终值，没有暴露中间算术步骤；算法计算结果相同。','subtotal=n·p；answer=subtotal−2','subtotal = count * price\nanswer = subtotal - 2',['problem'],{kind:'state',axes:['example','step','input1/input2/output']}),stage('answer','答案',[[answer]],'两种表达方式得到同一算术结果。本页不以脚本的正确性声称 LLM 的 CoT 一定正确。','answer=n·p−2','return answer',['work'],{kind:'state',axes:['example','answer','value']})],metrics:[{label:'总价（优惠前）',value:String(total)},{label:'最终答案',value:String(answer)}],observations:[show?`先算 ${count}×${price}=${total}，再减 2 得 ${answer}。`:`答案为 ${answer}。`,'这是公开教学算术脚本，不是真实模型的内部思维或推理证据。'],sourceCode}
 }
 if(id==='21') {
  const failed=s.failure??0,turn=s.turn??1,n=s.count??3,result=n*7
  const events=failed?[
   ['Plan','需要计算总价，先请求计算器。'],['Action',`multiply(${n},7)`],['Observation','模拟工具返回：暂时失败；没有数值结果。'],['Action',`retry multiply(${n},7)`],['Observation',`本地乘法函数返回 ${result}`],['Answer',`总价为 ${result}`]
  ]:[['Plan','需要计算总价，先请求计算器。'],['Action',`multiply(${n},7)`],['Observation',`本地乘法函数返回 ${result}`],['Answer',`总价为 ${result}`]]
  const shown=events.slice(0,Math.min(turn,events.length)),hasValue=shown.some(e=>e[0]==='Observation'&&e[1].includes('返回 '+result))
  const states=shown.map(([role,text],i)=>[i+1,['Plan','Action','Observation','Answer'].indexOf(role),role==='Observation'&&text.includes('返回 '+result)?result:0])
  return {knobs:[{key:'failure',title:'第一次工具返回',min:0,max:1,step:1,initial:0,labels:{0:'成功',1:'模拟失败'}},{key:'turn',title:'展开到第几步',min:1,max:6,step:1,initial:1},{key:'count',title:'物品数量',min:1,max:8,step:1,initial:3}],stages:[stage('request','任务与环境',[[n,7]],'任务：计算 n 个物品、每个 7 元的总价。本地脚本模拟环境，没有网络访问。','task=(n,price)','request = {count:n, price:7}',[],{kind:'state',axes:['episode','task','count/price']}),stage('history','行动—观察记录',states,'三列：步数、角色代码、已观察到的数值；非数值事件的 0 是占位，不是工具结果。角色代码 0计划、1行动、2观察、3答案。','contextₜ₊₁=contextₜ ⊕ actionₜ ⊕ observationₜ','history.append(action); history.append(tool_result)',['request'],{kind:'state',axes:['episode','event','step/role/value'],rows:shown.map(e=>e[0])}),stage('state','是否获得结果',[[hasValue?1:0,hasValue?result:0]],'第一列标记是否已有成功观察。未获得结果时第二列占位为 0，不能据此声称总价为 0。','answer allowed ⇔ successful observation','if observation.ok: answer(observation.value)',['history'],{kind:'state',axes:['episode','state','available/value']})],metrics:[{label:'当前事件',value:shown[shown.length-1][0]},{label:'结果已观察',value:hasValue?'是':'否'}],observations:shown.map(e=>`${e[0]}：${e[1]}`),sourceCode}
 }
 const benefit=s.benefit??.35,threshold=s.threshold??.2,base=[.3,.4,.25],empty=base.map(v=>v+.02),withResult=[Math.min(.98,base[0]+benefit),Math.max(.02,base[1]-.05),base[2]+.05]
 const losses=base.map((p,i)=>[-Math.log(p),-Math.log(empty[i]),-Math.log(withResult[i])]),gains=losses.map(row=>Math.min(row[0],row[1])-row[2]),keep=gains.map(g=>g>=threshold?1:0)
 return {knobs:[{key:'benefit',title:'候选 0 对正确 token 概率的改善',min:0,max:.65,step:.05,initial:.35},{key:'threshold',title:'保留阈值 τ',min:0,max:1,step:.05,initial:.2}],stages:[stage('candidates','三种候选调用',base.map((v,i)=>[i,v]),'候选分别代表计算器、无关检索、轻微有益检索。概率是人造的，未运行 API 或语言模型。','candidate calls c₁,c₂,c₃','candidates = sample_api_calls(text)',[],{kind:'state',axes:['example','call','id/base_probability'],rows:['计算器','无关检索','轻微有益检索']}),stage('probability','三种上下文的目标概率',base.map((p,i)=>[p,empty[i],withResult[i]]),'列：无调用、有调用无结果、有调用有结果。这里只考虑一个目标 token，完整论文还对后续 token 加权。','p(xnext|context)','p0, p_empty, p_result = score_next_token(contexts)',['candidates'],{kind:'measurement',axes:['example','candidate','no/empty/result']}),stage('loss','后续预测损失',losses,'对正确目标概率取负对数；概率越高损失越低。','L(z)=−log p(target|z)','losses = -log(probabilities)',['probability'],{kind:'measurement',axes:['example','candidate','Lno/Lempty/Lresult']}),stage('filter','筛选结果',gains.map((g,i)=>[g,threshold,keep[i]]),'先取两个基线损失的较小值，再减有结果的损失。收益达到阈值才保留。','min(Lno,Lempty)−Lresult ≥ τ','keep = minimum(loss_no, loss_empty) - loss_result >= threshold',['loss'],{kind:'measurement',axes:['example','candidate','gain/threshold/keep']})],metrics:[{label:'保留调用数',value:`${sum(keep)} / 3`},{label:'候选 0 改善量',value:fmt(gains[0])}],observations:['工具调用存在并不保证有益，筛选依据是后续预测改善。','本页不生成训练集、不调用外部工具。'],sourceCode}
}
