import {fields,list,text,string,number,integer,choice,object,sameLength} from './traceValidation'
import {generation} from './languageTraces'
const nullable=(v:unknown)=>v===null?null:string(v)
export function extractFinal(output:string){output=output.replace(/\r\n?/g,'\n');const lines=output.trim().split('\n'),matches=output.split('\n').flatMap(line=>{const m=line.match(/^FINAL:[ \t]*([+-]?\d{1,12})[ \t]*$/);return m&&m[0]===line?[m[1]]:[]});if(matches.length!==1||!/^FINAL:[ \t]*[+-]?\d{1,12}[ \t]*$/.test(lines[lines.length-1]))return null;return String(Number(matches[0]))}
const result=(v:unknown)=>{const g=generation(v),o=object(v),answer=nullable(o.answer);if(answer!==extractFinal(g.output))throw Error('提取答案与实际输出不一致');return {...g,answer}}
const taskBase=fields({id:text,category:text,question:text,expected:text})
function task(v:unknown){const d=taskBase(v);if(!/^-?\d{1,12}$/.test(d.expected)||String(Number(d.expected))!==d.expected)throw Error('目标需要规范整数');return d}
const auditSchema=fields({format:choice('solution-audit-v2'),route:choice('substitute','original-record'),dataset_version:text,tasks:list((v:unknown)=>{const t=task(v),r=list((x:unknown)=>({...result(x),condition:choice('direct','worked')(object(x).condition)}),2,2)(object(v).responses);if(r[0].condition!=='direct'||r[1].condition!=='worked')throw Error('需要direct/worked顺序');return {...t,responses:r}},1,30)})
const groupSchema=fields({format:choice('reward-group-v2'),route:choice('substitute','R1','R1-Zero'),dataset_version:text,tasks:list((v:unknown)=>({...task(v),answers:list(result,2,32)(object(v).answers)}),1,30)})
export function parseAudit(v:unknown){const d=auditSchema(v);if(new Set(d.tasks.map(t=>t.id)).size!==d.tasks.length)throw Error('题目ID重复');return d}
export function parseGroup(v:unknown){const d=groupSchema(v);if(new Set(d.tasks.map(t=>t.id)).size!==d.tasks.length)throw Error('题目ID重复');for(const t of d.tasks)if(t.answers.some(a=>a.text!==t.answers[0].text))throw Error('同组候选必须使用同一个实际提示');return d}
export function rewardStats(rewards:number[]){const mean=rewards.reduce<number>((a,b)=>a+b,0)/(rewards.length||1),std=Math.sqrt(rewards.reduce<number>((s,r)=>s+(r-mean)**2,0)/(rewards.length||1));return {mean,std,advantages:rewards.map(r=>std===0?0:(r-mean)/std)}}
const boundedLoss=(v:unknown)=>{const n=number(v);if(n<0||n>1e6)throw Error('NLL/权重需要0–10^6');return n}
const tool=fields({call:text,tool_return:string,target_text:text,target_ids:list(integer,1,64),target_tokens:list(text,1,64),weights:list(boundedLoss,1,64),loss_without:list(boundedLoss,1,64),loss_empty:list(boundedLoss,1,64),loss_with:list(boundedLoss,1,64),contexts:list(fields({prefix:text,prefix_ids:list(integer,1,4096),target_start:integer}),3,3)})
export function parseTools(v:unknown){const d=fields({format:choice('tool-score-v2'),candidates:list(tool,1,50)})(v);for(const c of d.candidates){sameLength(c.target_ids,c.target_tokens,c.weights,c.loss_without,c.loss_empty,c.loss_with);if(c.weights.reduce<number>((s,w)=>s+w,0)<=0)throw Error('权重总和需要大于0');if(c.contexts.some(x=>x.target_start!==x.prefix_ids.length))throw Error('目标起点不一致')}return d}
export const parsePreferences=fields({items:list(fields({prompt:text,responses:list(fields({stage:text,text,reward:(v:unknown)=>{if(v===null)return null;const n=number(v);if(Math.abs(n)>1e6)throw Error('奖励绝对值过大');return n}}),2,6)}),1,100)})
