import { fields,list,text,string,image,integer,number,positive,probability,choice } from './traceValidation'
const vector=list(number,1,2048)
const vitSchema=fields({image_size:integer,patch_size:positive,hidden_size:integer,position_vectors:list(vector,1,4096),patch_delta:list(number,1,4096),layer_shapes:list(list(integer,3,3),1,100),conditions:list(fields({name:choice('original','changed'),image,input_sha256:text,top:list(fields({id:integer,label:text,p:probability}),1,5),patch_vectors:list(vector,1,4096),token_vectors:list(vector,1,4096)}),2,2),reference_class:fields({label:text,probabilities:list(probability,2,2)})})
export function parseVit(v:unknown){const d=vitSchema(v);const count=(d.image_size/d.patch_size)**2,preview=Math.min(16,d.hidden_size);if(d.image_size!==224||!Number.isInteger(d.patch_size)||!Number.isInteger(Math.sqrt(count))||!d.hidden_size)throw Error('ViT尺寸不支持');if(d.conditions[0].name!=='original'||d.conditions[1].name!=='changed')throw Error('需要按原图、干预图顺序记录');if(d.patch_delta.length!==count||d.position_vectors.length!==count||d.patch_delta.some(x=>x<0))throw Error('patch数量不一致');for(const c of d.conditions)if(c.patch_vectors.length!==count||c.token_vectors.length!==count)throw Error('向量数量不符');for(const vectors of [d.position_vectors,...d.conditions.flatMap(c=>[c.patch_vectors,c.token_vectors])])if(vectors.some(x=>x.length!==preview))throw Error('向量预览维度不符');for(const s of d.layer_shapes)if(s[0]!==2||s[1]!==count+1||s[2]!==d.hidden_size)throw Error('层形状与输入不符');return d}
const box=(v:unknown)=>v===null?null:list(number,4,4)(v)
const samSchema=fields({image,width:integer,height:integer,cases:list(fields({name:text,points:list(fields({x:number,y:number,label:choice('positive','negative')}),0,100),box,masks:list(fields({image,predicted_iou:number}),1,6)}),1,30)})
export function parseSam(v:unknown){const d=samSchema(v);if(!d.width||!d.height||d.width*d.height>16_000_000)throw Error('图像尺寸不支持');for(const c of d.cases){for(const p of c.points)if(p.x<0||p.y<0||p.x>=d.width||p.y>=d.height)throw Error('提示点越界');if(c.box){const [x1,y1,x2,y2]=c.box;if(x1<0||y1<0||x2>d.width||y2>d.height||x1>=x2||y1>=y2)throw Error('框坐标无效')}}return d}
const nullableImage=(v:unknown)=>v===null?null:image(v)
const llavaSchema=fields({question:text,conditions:list(fields({name:text,condition:choice('original','occluded','no_image'),image:nullableImage,answer:string}),2,3)})
export function parseLlava(v:unknown){const d=llavaSchema(v);if(new Set(d.conditions.map(c=>c.condition)).size!==d.conditions.length||!d.conditions.some(c=>c.condition==='original')||!d.conditions.some(c=>c.condition==='occluded'))throw Error('需要原图/遮挡图各一次，无图可选');for(const c of d.conditions)if((c.condition==='no_image')!==(c.image===null))throw Error('no_image必须无图，其它条件必须带图');return d}
